import type {
  MetricCardData,
  RevenueTrendPoint,
  OutstandingPaymentItem,
  MethodDistributionItem,
  TherapistPayoutItem,
  RecentActivityItem,
  InvoiceItem,
  TransactionItem,
  PackageItem,
  RefundItem,
  PayoutRecordItem,
} from './types';

export const METRIC_CARDS_DATA: MetricCardData[] = [
  {
    title: 'REVENUE',
    value: '₹12.4M',
    subtext: '+12% vs last month',
    badgeType: 'success',
    iconType: 'trend',
  },
  {
    title: 'OUTSTANDING',
    badge: 'NEEDS ATTENTION',
    value: '₹1.2M',
    subtext: 'Due from 24 patients',
    badgeType: 'warning',
    iconType: 'attention',
  },
  {
    title: 'COLLECTED TODAY',
    value: '₹84k',
    subtext: '12 transactions',
    iconType: 'today',
  },
  {
    title: 'PENDING REFUNDS',
    value: '5',
    subtext: 'Awaiting approval',
    iconType: 'refunds',
  },
  {
    title: 'THERAPIST PAYOUTS',
    value: '₹4.2M',
    subtext: 'Due Oct 31',
    iconType: 'payouts',
    isHighlighted: true,
  },
];

export const REVENUE_TREND_DATA: RevenueTrendPoint[] = [
  { label: 'OCT 01', netRevenue: 42, payouts: 22 },
  { label: 'OCT 08', netRevenue: 54, payouts: 28 },
  { label: 'OCT 15', netRevenue: 82, payouts: 40 },
  { label: 'OCT 22', netRevenue: 64, payouts: 32 },
  { label: 'OCT 31', netRevenue: 76, payouts: 36 },
];

export const OUTSTANDING_PAYMENTS_DATA: OutstandingPaymentItem[] = [
  {
    id: 'out-1',
    patientName: 'Sanya Malhotra',
    initials: 'SM',
    invoiceId: 'INV-2023-892',
    amount: 14500,
    dueDateLabel: 'Overdue 4d',
    isOverdue: true,
  },
  {
    id: 'out-2',
    patientName: 'Arjun Kapoor',
    initials: 'AK',
    invoiceId: 'INV-2023-905',
    amount: 8200,
    dueDateLabel: 'Due Oct 28',
    isOverdue: false,
  },
  {
    id: 'out-3',
    patientName: 'Rohan Joshi',
    initials: 'RJ',
    invoiceId: 'INV-2023-911',
    amount: 12000,
    dueDateLabel: 'Due Oct 30',
    isOverdue: false,
  },
];

export const METHOD_DISTRIBUTION_DATA: MethodDistributionItem[] = [
  { method: 'UPI', percentage: 60, color: '#1E40AF', amount: '₹7.44M' },
  { method: 'Card', percentage: 25, color: '#06B6D4', amount: '₹3.10M' },
  { method: 'Net Banking', percentage: 15, color: '#818CF8', amount: '₹1.86M' },
];

export const UPCOMING_PAYOUTS_DATA: TherapistPayoutItem[] = [
  {
    id: 'pay-1',
    name: 'Dr. Ananya Ray',
    role: 'Clinical Lead',
    avatarUrl: 'https://images.unsplash.com/photo-1594824813566-88855ce78907?w=150&auto=format&fit=crop&q=80',
    accumulatedAmount: 124000,
    targetPercentage: 82,
  },
  {
    id: 'pay-2',
    name: 'Dr. Vikram Seth',
    role: 'Physiotherapist',
    avatarUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=150&auto=format&fit=crop&q=80',
    accumulatedAmount: 86500,
    targetPercentage: 60,
  },
  {
    id: 'pay-3',
    name: 'Meera Nair',
    role: 'Counselor',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    accumulatedAmount: 94200,
    targetPercentage: 75,
  },
];

export const RECENT_ACTIVITY_DATA: RecentActivityItem[] = [
  {
    id: 'act-1',
    type: 'success',
    title: 'Payment Successful',
    description: '₹12,400 received from Rahul Khanna via UPI.',
    timeAgo: '2 MINUTES AGO',
    amount: '₹12,400',
  },
  {
    id: 'act-2',
    type: 'failed',
    title: 'Transaction Failed',
    description: '₹4,500 declined for Anita Desai. Card expired.',
    timeAgo: '15 MINUTES AGO',
    amount: '₹4,500',
  },
  {
    id: 'act-3',
    type: 'scheduled',
    title: 'Payout Scheduled',
    description: 'Monthly settlement for Dr. Vikram Seth approved.',
    timeAgo: '1 HOUR AGO',
  },
  {
    id: 'act-4',
    type: 'refund',
    title: 'Refund Requested',
    description: '₹3,000 for Session Cancellation (Patient: Kabir S.).',
    timeAgo: '3 HOURS AGO',
    amount: '₹3,000',
  },
];

export const MOCK_INVOICES: InvoiceItem[] = [
  {
    id: 'inv-1',
    invoiceNumber: 'INV-2023-892',
    patientName: 'Sanya Malhotra',
    patientEmail: 'sanya.m@example.com',
    therapistName: 'Dr. Ananya Ray',
    issueDate: '2026-10-01',
    dueDate: '2026-10-06',
    amount: 14500,
    status: 'Overdue',
    paymentMethod: 'UPI',
  },
  {
    id: 'inv-2',
    invoiceNumber: 'INV-2023-905',
    patientName: 'Arjun Kapoor',
    patientEmail: 'arjun.k@example.com',
    therapistName: 'Dr. Vikram Seth',
    issueDate: '2026-10-14',
    dueDate: '2026-10-28',
    amount: 8200,
    status: 'Pending',
    paymentMethod: 'Credit Card',
  },
  {
    id: 'inv-3',
    invoiceNumber: 'INV-2023-911',
    patientName: 'Rohan Joshi',
    patientEmail: 'rohan.j@example.com',
    therapistName: 'Meera Nair',
    issueDate: '2026-10-15',
    dueDate: '2026-10-30',
    amount: 12000,
    status: 'Pending',
    paymentMethod: 'Net Banking',
  },
  {
    id: 'inv-4',
    invoiceNumber: 'INV-2023-888',
    patientName: 'Rahul Khanna',
    patientEmail: 'rahul.khanna@example.com',
    therapistName: 'Dr. Ananya Ray',
    issueDate: '2026-10-10',
    dueDate: '2026-10-10',
    amount: 12400,
    status: 'Paid',
    paymentMethod: 'UPI',
  },
  {
    id: 'inv-5',
    invoiceNumber: 'INV-2023-880',
    patientName: 'Priya Sharma',
    patientEmail: 'priya.s@example.com',
    therapistName: 'Dr. Rajesh Verma',
    issueDate: '2026-10-08',
    dueDate: '2026-10-18',
    amount: 18500,
    status: 'Paid',
    paymentMethod: 'Credit Card',
  },
  {
    id: 'inv-6',
    invoiceNumber: 'INV-2023-875',
    patientName: 'Kabir Singh',
    patientEmail: 'kabir.s@example.com',
    therapistName: 'Meera Nair',
    issueDate: '2026-10-05',
    dueDate: '2026-10-15',
    amount: 9500,
    status: 'Paid',
    paymentMethod: 'UPI',
  },
];

export const MOCK_TRANSACTIONS: TransactionItem[] = [
  {
    id: 'txn-1',
    transactionId: 'TXN-998201',
    patientName: 'Rahul Khanna',
    method: 'UPI',
    amount: 12400,
    type: 'Payment',
    timestamp: 'Today, 11:52 AM',
    status: 'Completed',
  },
  {
    id: 'txn-2',
    transactionId: 'TXN-998198',
    patientName: 'Anita Desai',
    method: 'Credit Card',
    amount: 4500,
    type: 'Payment',
    timestamp: 'Today, 11:39 AM',
    status: 'Failed',
  },
  {
    id: 'txn-3',
    transactionId: 'TXN-998180',
    patientName: 'Dr. Vikram Seth',
    method: 'Net Banking',
    amount: 86500,
    type: 'Payout',
    timestamp: 'Today, 10:54 AM',
    status: 'Completed',
  },
  {
    id: 'txn-4',
    transactionId: 'TXN-998150',
    patientName: 'Kabir Singh',
    method: 'UPI',
    amount: 3000,
    type: 'Refund',
    timestamp: 'Today, 08:54 AM',
    status: 'Processing',
  },
  {
    id: 'txn-5',
    transactionId: 'TXN-998110',
    patientName: 'Priya Sharma',
    method: 'Credit Card',
    amount: 18500,
    type: 'Payment',
    timestamp: 'Yesterday, 04:30 PM',
    status: 'Completed',
  },
];

export const MOCK_PACKAGES: PackageItem[] = [
  {
    id: 'pkg-1',
    packageName: 'ACL Post-Op Recovery Plan (12 Sessions)',
    patientName: 'Sanya Malhotra',
    totalSessions: 12,
    completedSessions: 8,
    totalAmount: 36000,
    paidAmount: 24000,
    status: 'Active',
  },
  {
    id: 'pkg-2',
    packageName: 'Chronic Back Spine Rehab (8 Sessions)',
    patientName: 'Arjun Kapoor',
    totalSessions: 8,
    completedSessions: 3,
    totalAmount: 24000,
    paidAmount: 12000,
    status: 'Active',
  },
  {
    id: 'pkg-3',
    packageName: 'Stroke Neuro Mobility Program (20 Sessions)',
    patientName: 'Rohan Joshi',
    totalSessions: 20,
    completedSessions: 20,
    totalAmount: 60000,
    paidAmount: 60000,
    status: 'Completed',
  },
];

export const MOCK_REFUNDS: RefundItem[] = [
  {
    id: 'ref-1',
    refundId: 'REF-2023-041',
    patientName: 'Kabir Singh',
    amount: 3000,
    reason: 'Session Cancellation due to illness',
    requestDate: '2026-10-27',
    status: 'Awaiting Approval',
  },
  {
    id: 'ref-2',
    refundId: 'REF-2023-040',
    patientName: 'Anita Desai',
    amount: 4500,
    reason: 'Double charged on invoice #870',
    requestDate: '2026-10-25',
    status: 'Awaiting Approval',
  },
  {
    id: 'ref-3',
    refundId: 'REF-2023-038',
    patientName: 'Meenakshi Iyer',
    amount: 2200,
    reason: 'Therapist rescheduled slot unavailable',
    requestDate: '2026-10-22',
    status: 'Approved',
  },
];

export const MOCK_PAYOUTS: PayoutRecordItem[] = [
  {
    id: 'payout-1',
    therapistName: 'Dr. Ananya Ray',
    role: 'Clinical Lead',
    period: 'Oct 01 - Oct 31',
    sessionCount: 124,
    grossEarnings: 155000,
    platformDeduction: 31000,
    netPayout: 124000,
    status: 'Scheduled',
    dueDate: '2026-10-31',
  },
  {
    id: 'payout-2',
    therapistName: 'Dr. Vikram Seth',
    role: 'Physiotherapist',
    period: 'Oct 01 - Oct 31',
    sessionCount: 92,
    grossEarnings: 108125,
    platformDeduction: 21625,
    netPayout: 86500,
    status: 'Scheduled',
    dueDate: '2026-10-31',
  },
  {
    id: 'payout-3',
    therapistName: 'Meera Nair',
    role: 'Counselor',
    period: 'Oct 01 - Oct 31',
    sessionCount: 105,
    grossEarnings: 117750,
    platformDeduction: 23550,
    netPayout: 94200,
    status: 'Scheduled',
    dueDate: '2026-10-31',
  },
];
