services:
  - type: web
    name: physiotherapy-user-service
    env: docker
    dockerContext: ./backend/user-service
    dockerfilePath: ./backend/user-service/Dockerfile
    region: singapore
    plan: free
    envVars:
      - key: PORT
        value: 5001
      - key: NODE_ENV
        value: production
      - key: FIREBASE_PROJECT_ID
        value: physicotherephy-c28dd
      - key: CORS_ORIGIN
        value: "*"
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false

  - type: web
    name: physiotherapy-appointment-service
    env: docker
    dockerContext: ./backend/appointment-service
    dockerfilePath: ./backend/appointment-service/Dockerfile
    region: singapore
    plan: free
    envVars:
      - key: PORT
        value: 5002
      - key: NODE_ENV
        value: production
      - key: FIREBASE_PROJECT_ID
        value: physicotherephy-c28dd
      - key: CORS_ORIGIN
        value: "*"
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false

  - type: web
    name: physiotherapy-payment-service
    env: docker
    dockerContext: ./backend/payment-service
    dockerfilePath: ./backend/payment-service/Dockerfile
    region: singapore
    plan: free
    envVars:
      - key: PORT
        value: 5003
      - key: NODE_ENV
        value: production
      - key: FIREBASE_PROJECT_ID
        value: physicotherephy-c28dd
      - key: CORS_ORIGIN
        value: "*"
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
