import type { Therapist } from './types';

export const INITIAL_THERAPISTS: Therapist[] = [
  {
    id: 't-1',
    name: 'Dr. Arjun Mehta',
    degree: 'BPT, MPT',
    experience: '12 Years Exp.',
    avatarUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=150&auto=format&fit=crop&q=80',
    specializations: ['Sports Rehab', 'Orthopedic'],
    patientsCount: 42,
    availability: 'Available Today',
    rating: 4.9,
    status: 'ACTIVE',
    email: 'arjun.mehta@onemedical.com',
    phone: '+1 (555) 234-5678',
    location: 'Building A, Room 204',
    bio: 'Specialist in sports biomechanics, joint mobilization, and post-surgical athletic rehabilitation.',
    workingHours: '09:00 AM - 05:00 PM',
  },
  {
    id: 't-2',
    name: 'Dr. Priya Sharma',
    degree: 'BPT',
    experience: '8 Years Exp.',
    avatarUrl: 'https://images.unsplash.com/photo-1594824813566-78a933758f46?w=150&auto=format&fit=crop&q=80',
    specializations: ['Neurological', 'MSK'],
    patientsCount: 28,
    availability: 'Busy',
    rating: 4.8,
    status: 'ACTIVE',
    email: 'priya.sharma@onemedical.com',
    phone: '+1 (555) 345-6789',
    location: 'Building B, Room 102',
    bio: 'Expert in neuro-rehabilitation, stroke recovery, and musculoskeletal pain management.',
    workingHours: '10:00 AM - 06:00 PM',
  },
  {
    id: 't-3',
    name: 'Dr. Ananya Iyer',
    degree: 'BPT, MPT',
    experience: '10 Years Exp.',
    avatarUrl: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=150&auto=format&fit=crop&q=80',
    specializations: ['Pelvic Health', 'Pediatrics'],
    patientsCount: 35,
    availability: 'Available Today',
    rating: 4.9,
    status: 'ACTIVE',
    email: 'ananya.iyer@onemedical.com',
    phone: '+1 (555) 456-7890',
    location: 'Building A, Room 108',
    bio: 'Dedicated practitioner for pelvic floor therapy and pediatric developmental physical therapy.',
    workingHours: '08:30 AM - 04:30 PM',
  },
  {
    id: 't-4',
    name: 'Dr. Rajesh Kumar',
    degree: 'BPT, PhD',
    experience: '22 Years Exp.',
    initials: 'RK',
    specializations: ['Geriatrics', 'Manual Therapy'],
    patientsCount: 15,
    availability: 'On Leave',
    rating: 5.0,
    status: 'INACTIVE',
    email: 'rajesh.kumar@onemedical.com',
    phone: '+1 (555) 567-8901',
    location: 'Building C, Room 301',
    bio: 'Senior clinical fellow specializing in geriatric care, spinal manual adjustments, and chronic pain treatment.',
    workingHours: 'On Leave (Returns Sept 1)',
  },
  {
    id: 't-5',
    name: 'Dr. Rohan Kapoor',
    degree: 'BPT, MPT (Cardiopulmonary)',
    experience: '15 Years Exp.',
    avatarUrl: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=150&auto=format&fit=crop&q=80',
    specializations: ['Sports Rehab', 'Post-Op Rehab'],
    patientsCount: 31,
    availability: 'Available Today',
    rating: 4.9,
    status: 'ACTIVE',
    email: 'rohan.kapoor@onemedical.com',
    phone: '+1 (555) 678-9012',
    location: 'Building A, Room 210',
    bio: 'Post-operative recovery and endurance training specialist for professional athletes.',
    workingHours: '09:00 AM - 05:00 PM',
  },
  {
    id: 't-6',
    name: 'Dr. Dev Mukherjee',
    degree: 'BPT, MSPT',
    experience: '7 Years Exp.',
    avatarUrl: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=150&auto=format&fit=crop&q=80',
    specializations: ['Neurological', 'MSK'],
    patientsCount: 22,
    availability: 'Busy',
    rating: 4.7,
    status: 'ACTIVE',
    email: 'dev.mukherjee@onemedical.com',
    phone: '+1 (555) 789-0123',
    location: 'Building B, Room 105',
    bio: 'Focused on musculoskeletal injury recovery and postural alignment exercises.',
    workingHours: '11:00 AM - 07:00 PM',
  },
  {
    id: 't-7',
    name: 'Dr. Meera Nambiar',
    degree: 'BPT, MPT (Neuro)',
    experience: '11 Years Exp.',
    avatarUrl: 'https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=150&auto=format&fit=crop&q=80',
    specializations: ['Neurological', 'Orthopedic'],
    patientsCount: 39,
    availability: 'Available Today',
    rating: 4.9,
    status: 'ACTIVE',
    email: 'meera.nambiar@onemedical.com',
    phone: '+1 (555) 890-1234',
    location: 'Building A, Room 201',
    bio: 'Specializes in neuro-rehabilitation and spinal cord movement therapies.',
    workingHours: '08:00 AM - 04:00 PM',
  },
  {
    id: 't-8',
    name: 'Dr. Siddharth Verma',
    degree: 'BPT, DPT',
    experience: '14 Years Exp.',
    initials: 'SV',
    specializations: ['Orthopedic', 'Manual Therapy'],
    patientsCount: 26,
    availability: 'On Leave',
    rating: 4.8,
    status: 'INACTIVE',
    email: 'siddharth.verma@onemedical.com',
    phone: '+1 (555) 901-2345',
    location: 'Building C, Room 304',
    bio: 'Experienced in spine mobilization, deep tissue manual therapy, and joint manipulation.',
    workingHours: 'On Leave',
  },
  {
    id: 't-9',
    name: 'Dr. Sneha Kulkarni',
    degree: 'BPT, MPT (Pediatrics)',
    experience: '9 Years Exp.',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    specializations: ['Pediatrics', 'Pelvic Health'],
    patientsCount: 33,
    availability: 'Available Today',
    rating: 4.9,
    status: 'ACTIVE',
    email: 'sneha.kulkarni@onemedical.com',
    phone: '+1 (555) 012-3456',
    location: 'Building B, Room 112',
    bio: 'Focused on pediatric physical growth milestones and adolescent postural rehabilitation.',
    workingHours: '09:00 AM - 05:00 PM',
  },
  {
    id: 't-10',
    name: 'Dr. Vikramaditya Singh',
    degree: 'BPT, MPT (Sports)',
    experience: '18 Years Exp.',
    avatarUrl: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&auto=format&fit=crop&q=80',
    specializations: ['Sports Rehab', 'Geriatrics'],
    patientsCount: 44,
    availability: 'Busy',
    rating: 5.0,
    status: 'ACTIVE',
    email: 'vikram.singh@onemedical.com',
    phone: '+1 (555) 123-4567',
    location: 'Building A, Room 305',
    bio: 'Head of sports medicine and elderly physical mobility programs.',
    workingHours: '08:00 AM - 04:00 PM',
  },
];
