import type { Therapist } from './types';

export const INITIAL_THERAPISTS: Therapist[] = [
  {
    id: 'th-1',
    name: 'Dr. Ananya Sharma',
    degree: 'MPT (Ortho), BPT',
    experience: '8+ Years Exp',
    specializations: ['Sports Rehab', 'Orthopedic', 'Spine Care'],
    patientsCount: 28,
    availability: 'Available Today',
    rating: 4.9,
    status: 'ACTIVE',
    email: 'ananya.sharma@physio.com',
    phone: '+91 98765 43210',
    avatarUrl: 'https://images.unsplash.com/photo-1594824813566-88855ce78c00?w=150&auto=format&fit=crop&q=80',
    initials: 'AS',
    location: 'Main Clinic - Room 102',
    bio: 'Senior Sports Physiotherapist specializing in knee joint replacement and rotator cuff rehabilitation.',
    workingHours: '09:00 AM - 05:00 PM',
  },
  {
    id: 'th-2',
    name: 'Dr. Rohan Kapoor',
    degree: 'MPT (Neuro), BPT',
    experience: '10+ Years Exp',
    specializations: ['Neurological', 'MSK', 'Post-Op Rehab'],
    patientsCount: 34,
    availability: 'Available Today',
    rating: 4.8,
    status: 'ACTIVE',
    email: 'rohan.kapoor@physio.com',
    phone: '+91 98765 43211',
    avatarUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=150&auto=format&fit=crop&q=80',
    initials: 'RK',
    location: 'Main Clinic - Room 104',
    bio: 'Lead Neuro Physiotherapist focusing on stroke recovery, spinal injury, and gait correction.',
    workingHours: '10:00 AM - 06:00 PM',
  },
  {
    id: 'th-3',
    name: 'Dr. Dev Mukherjee',
    degree: 'MPT (Sports), BPT',
    experience: '6+ Years Exp',
    specializations: ['Sports Rehab', 'Manual Therapy', 'ACL Recovery'],
    patientsCount: 22,
    availability: 'Busy',
    rating: 4.9,
    status: 'ACTIVE',
    email: 'dev.mukherjee@physio.com',
    phone: '+91 98765 43212',
    avatarUrl: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=150&auto=format&fit=crop&q=80',
    initials: 'DM',
    location: 'Sports Rehab Wing',
    bio: 'Specialist in athletic conditioning, dry needling, and sports performance optimization.',
    workingHours: '08:00 AM - 04:00 PM',
  },
  {
    id: 'th-4',
    name: 'Dr. Priya Patel',
    degree: 'MPT (Pelvic Health), BPT',
    experience: '7+ Years Exp',
    specializations: ['Pelvic Health', 'Pediatrics', 'Chronic Pain'],
    patientsCount: 19,
    availability: 'Available Today',
    rating: 4.7,
    status: 'ACTIVE',
    email: 'priya.patel@physio.com',
    phone: '+91 98765 43213',
    avatarUrl: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=150&auto=format&fit=crop&q=80',
    initials: 'PP',
    location: 'Pediatric Care Unit',
    bio: 'Dedicated therapist with expertise in women’s wellness, pelvic rehabilitation, and pediatric motor skills.',
    workingHours: '09:00 AM - 05:00 PM',
  },
  {
    id: 'th-5',
    name: 'Dr. Vikram Malhotra',
    degree: 'DPT, MPT (Geriatrics)',
    experience: '12+ Years Exp',
    specializations: ['Geriatrics', 'Orthopedic', 'Post-Op Rehab'],
    patientsCount: 31,
    availability: 'On Leave',
    rating: 4.9,
    status: 'INACTIVE',
    email: 'vikram.malhotra@physio.com',
    phone: '+91 98765 43214',
    avatarUrl: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=150&auto=format&fit=crop&q=80',
    initials: 'VM',
    location: 'Senior Care Section',
    bio: 'Expert in geriatric mobility, arthritis management, and post-hip surgery physical therapy.',
    workingHours: '11:00 AM - 07:00 PM',
  },
  {
    id: 'th-6',
    name: 'Dr. Meera Reddy',
    degree: 'MPT (Cardiopulmonary), BPT',
    experience: '5+ Years Exp',
    specializations: ['MSK', 'Manual Therapy', 'Rehab'],
    patientsCount: 15,
    availability: 'Available Today',
    rating: 4.8,
    status: 'ACTIVE',
    email: 'meera.reddy@physio.com',
    phone: '+91 98765 43215',
    avatarUrl: 'https://images.unsplash.com/photo-1594824813566-88855ce78c00?w=150&auto=format&fit=crop&q=80',
    initials: 'MR',
    location: 'Cardio Rehab Wing',
    bio: 'Focuses on pulmonary rehabilitation, posture correction, and myofascial release therapy.',
    workingHours: '09:30 AM - 05:30 PM',
  },
];

