import type { Patient } from './types';

export const INITIAL_PATIENTS: Patient[] = [
  {
    id: 'p-0',
    patientId: '#OM-2024',
    name: 'Sanya Malhotra',
    age: 32,
    gender: 'Female',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=300&auto=format&fit=crop&q=80',
    condition: 'Lower Back Pain',
    therapistName: 'Dr. Ananya Iyer',
    therapistInitials: 'AI',
    therapistAvatarBg: 'bg-teal-100 text-teal-700',
    nextAppointmentDate: '24 Feb',
    nextAppointmentTime: '10:30 AM',
    recoveryScore: 78,
    status: 'Active Treatment',
    phone: '+91 98765 12345',
    email: 'sanya.malhotra@example.com',
    joinedDate: 'Jan 10, 2024',
    notes: 'Lumbar spine stabilization program progressing very well.',
    painLevel: 'Moderate',
    programsAssignedCount: 3,
    sessionsCompleted: 18,
    sessionsTotal: 30,
    treatmentPlan: {
      title: 'Lumbar Spine Stabilization',
      subtitle: 'Focus on deep core activation and progressive weight loading.',
      progress: 80,
      frequency: '3x per week',
      duration: '12 Weeks Plan',
    },
    goals: [
      { id: 'g-1', text: 'Walk 3km without pain intensification', category: 'SHORT TERM', completed: true },
      { id: 'g-2', text: 'Return to recreational tennis practice', category: 'LONG TERM', completed: false },
      { id: 'g-3', text: 'Full lumbar flexion mobility (standard range)', category: 'SHORT TERM', completed: false },
    ],
    reports: [
      { id: 'r-1', title: 'MRI Scan - Lumbar Spine', date: 'Uploaded on 12 Feb 2024', size: '4.2MB', type: 'mri' },
      { id: 'r-2', title: 'Initial Assessment Report', date: 'Uploaded on 05 Feb 2024', size: '1.1MB', type: 'pdf' },
    ],
    upcomingAppointments: [
      { id: 'a-1', date: 'Feb 24', time: '10:30 AM - 11:30 AM', doctorName: 'Dr. Ananya Iyer', isNextSession: true },
      { id: 'a-2', date: 'March 02', time: '02:15 PM • Video Call', doctorName: 'Dr. Ananya Iyer', isNextSession: false },
    ],
    clinicalNotes: [
      { id: 'cn-1', text: '"Patient reports improved morning stiffness. Focusing on eccentric loading next session."', date: 'Feb 18, 2024', doctorName: 'Dr. Ananya Iyer' },
      { id: 'cn-2', text: '"Started new core stability protocol. Patient tolerated well but limited flexion observed."', date: 'Feb 11, 2024', doctorName: 'Dr. Ananya Iyer' },
    ],
  },
  {
    id: 'p-1',
    patientId: '#OM-8821',
    name: 'Arjun Mehra',
    age: 42,
    gender: 'Male',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    condition: 'Post-Op Rehab',
    therapistName: 'Dr. Ananya Sharma',
    therapistInitials: 'AS',
    therapistAvatarBg: 'bg-purple-100 text-purple-700',
    nextAppointmentDate: 'Oct 12, 2023',
    nextAppointmentTime: '09:30 AM',
    recoveryScore: 78,
    status: 'Active Treatment',
    phone: '+91 98765 43210',
    email: 'arjun.mehra@example.com',
    joinedDate: 'Aug 15, 2023',
    notes: 'Recovering smoothly post knee arthroscopy. Range of motion improved by 25 degrees.',
  },
  {
    id: 'p-2',
    patientId: '#OM-8845',
    name: 'Priya Iyer',
    age: 29,
    gender: 'Female',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    condition: 'Neuropathy',
    therapistName: 'Dr. Rohan Kapoor',
    therapistInitials: 'RK',
    therapistAvatarBg: 'bg-blue-100 text-blue-700',
    nextAppointmentDate: 'Oct 14, 2023',
    nextAppointmentTime: '02:15 PM',
    recoveryScore: 45,
    status: 'Observation',
    phone: '+91 98123 45678',
    email: 'priya.iyer@example.com',
    joinedDate: 'Sep 01, 2023',
    notes: 'Peripheral nerve stimulation ongoing. Monitoring sensory response weekly.',
  },
  {
    id: 'p-3',
    patientId: '#OM-8790',
    name: 'Vikram Malhotra',
    age: 74,
    gender: 'Male',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    condition: 'Hypertension',
    therapistName: 'Dr. Dev Mukherjee',
    therapistInitials: 'DM',
    therapistAvatarBg: 'bg-teal-100 text-teal-700',
    nextAppointmentDate: 'Tomorrow',
    nextAppointmentTime: '11:00 AM',
    recoveryScore: 92,
    status: 'Recovered',
    phone: '+91 99000 11223',
    email: 'vikram.m@example.com',
    joinedDate: 'Jul 10, 2023',
    notes: 'Blood pressure stabilized under low-impact cardio rehab program.',
  },
  {
    id: 'p-4',
    patientId: '#OM-8912',
    name: 'Sanya Nair',
    age: 51,
    gender: 'Female',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    condition: 'Rehab',
    therapistName: 'Dr. Ananya Sharma',
    therapistInitials: 'AS',
    therapistAvatarBg: 'bg-purple-100 text-purple-700',
    nextAppointmentDate: 'Oct 20, 2023',
    nextAppointmentTime: '08:00 AM',
    recoveryScore: 61,
    status: 'Active Treatment',
    phone: '+91 97654 32109',
    email: 'sanya.nair@example.com',
    joinedDate: 'Sep 12, 2023',
    notes: 'Shoulder impingement therapy session 4 complete. Home exercise compliance good.',
  },
  {
    id: 'p-5',
    patientId: '#OM-8950',
    name: 'Kabir Singh',
    age: 34,
    gender: 'Male',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    condition: 'ACL Recovery',
    therapistName: 'Dr. Dev Mukherjee',
    therapistInitials: 'DM',
    therapistAvatarBg: 'bg-teal-100 text-teal-700',
    nextAppointmentDate: 'Oct 22, 2023',
    nextAppointmentTime: '10:00 AM',
    recoveryScore: 84,
    status: 'Active Treatment',
    phone: '+91 98888 77766',
    email: 'kabir.singh@example.com',
    joinedDate: 'Jun 20, 2023',
    notes: 'ACL reconstruction week 14. Plyometric progression started.',
  },
  {
    id: 'p-6',
    patientId: '#OM-8962',
    name: 'Ananya Patel',
    age: 28,
    gender: 'Female',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    condition: 'Orthopedic',
    therapistName: 'Dr. Rohan Kapoor',
    therapistInitials: 'RK',
    therapistAvatarBg: 'bg-blue-100 text-blue-700',
    nextAppointmentDate: 'Oct 25, 2023',
    nextAppointmentTime: '04:00 PM',
    recoveryScore: 53,
    status: 'Observation',
    phone: '+91 97777 66655',
    email: 'ananya.patel@example.com',
    joinedDate: 'Aug 28, 2023',
    notes: 'Lumbar spine stabilization program. Mild lower back tightness post work.',
  },
  {
    id: 'p-7',
    patientId: '#OM-8975',
    name: 'Rajesh Kumar',
    age: 63,
    gender: 'Male',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    condition: 'Chronic Pain',
    therapistName: 'Dr. Ananya Sharma',
    therapistInitials: 'AS',
    therapistAvatarBg: 'bg-purple-100 text-purple-700',
    nextAppointmentDate: 'Oct 28, 2023',
    nextAppointmentTime: '01:30 PM',
    recoveryScore: 39,
    status: 'Active Treatment',
    phone: '+91 96666 55544',
    email: 'rajesh.k@example.com',
    joinedDate: 'Sep 18, 2023',
    notes: 'Osteoarthritis management. Electrotherapy and hydrotherapy recommended.',
  },
  {
    id: 'p-8',
    patientId: '#OM-8990',
    name: 'Sunita Rao',
    age: 48,
    gender: 'Female',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    condition: 'Post-Op Rehab',
    therapistName: 'Dr. Dev Mukherjee',
    therapistInitials: 'DM',
    therapistAvatarBg: 'bg-teal-100 text-teal-700',
    nextAppointmentDate: 'Nov 01, 2023',
    nextAppointmentTime: '11:15 AM',
    recoveryScore: 95,
    status: 'Recovered',
    phone: '+91 95555 44433',
    email: 'sunita.rao@example.com',
    joinedDate: 'May 04, 2023',
    notes: 'Rotator cuff repair fully rehabbed. Cleared for normal daily activities.',
  },
];
