export const initialSeedPatients = [
  {
    patientId: '#OM-8492',
    name: 'Sagar Verma',
    age: 28,
    gender: 'Male',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    condition: 'Post-Op Rehab',
    therapistName: 'Dr. Ananya Sharma',
    therapistInitials: 'AS',
    therapistAvatarBg: 'bg-teal-50 text-teal-700',
    therapistSpecialization: 'Orthopedic & Post-Op Rehab',
    nextAppointmentDate: 'Today',
    nextAppointmentTime: '04:30 PM',
    recoveryScore: 88,
    status: 'Active Treatment',
    phone: '+91 98765 11111',
    email: 'sagar.verma@example.com',
    joinedDate: 'Jun 12, 2026',
    address: 'B-402, Green Park, New Delhi',
    bloodGroup: 'O+',
    emergencyContact: {
      name: 'Ramesh Verma',
      relation: 'Father',
      phone: '+91 98765 99999',
    },
    notes: 'ACL post-reconstruction week 6. Core stability & knee extension exercises progressing well.',
    painLevel: 'Mild',
    programsAssignedCount: 2,
    sessionsCompleted: 14,
    sessionsTotal: 20,
    treatmentPlan: {
      title: 'ACL Reconstruction Protocol v2',
      subtitle: '8-Week Accelerated Lower Limb Program',
      progress: 70,
      frequency: '3x Weekly',
      duration: '8 Weeks',
    },
    medicalHistory: {
      primaryDiagnosis: 'Right Knee ACL Reconstruction',
      severity: 'Moderate',
      allergies: ['Penicillin'],
      surgeries: ['ACL Reconstruction Surgery (May 2026)'],
      chronicConditions: ['None'],
      vitals: {
        bloodPressure: '120/80 mmHg',
        heartRate: '72 bpm',
        height: '178 cm',
        weight: '74 kg',
        bmi: '23.4',
      },
    },
    goals: [
      { id: 'g-1', text: 'Achieve 130° active knee flexion without lag', category: 'SHORT TERM', completed: true },
      { id: 'g-2', text: 'Single-leg balance stability for > 45 seconds', category: 'LONG TERM', completed: false },
    ],
    reports: [
      { id: 'rep-1', title: 'Post-Op MRI Knee Evaluation', date: 'Jul 04, 2026', size: '2.4 MB', type: 'mri' },
      { id: 'rep-2', title: 'Biomechanical Gait Analysis', date: 'Jul 20, 2026', size: '1.8 MB', type: 'pdf' },
    ],
    upcomingAppointments: [
      { id: 'apt-1', date: 'Today', time: '04:30 PM', doctorName: 'Dr. Ananya Sharma', type: 'Manual Therapy & ROM', status: 'upcoming' },
      { id: 'apt-2', date: 'Aug 16, 2026', time: '10:00 AM', doctorName: 'Dr. Ananya Sharma', type: 'Strength Progress Check', status: 'upcoming' },
    ],
    pastAppointments: [
      { id: 'apt-01', date: 'Aug 05, 2026', time: '11:00 AM', doctorName: 'Dr. Ananya Sharma', type: 'Post-Op Evaluation', status: 'completed' },
      { id: 'apt-02', date: 'Jul 28, 2026', time: '03:00 PM', doctorName: 'Dr. Ananya Sharma', type: 'Stitch Removal & Mobilization', status: 'completed' },
    ],
    payments: [
      { id: 'pay-1', date: 'Aug 01, 2026', amount: 3500, method: 'UPI / GPay', status: 'paid', invoiceNumber: 'INV-2026-081', description: 'Package Session 10-15' },
      { id: 'pay-2', date: 'Aug 12, 2026', amount: 1500, method: 'Credit Card', status: 'pending', invoiceNumber: 'INV-2026-092', description: 'Knee Brace & Tape Assessment' },
    ],
    programs: [
      { id: 'prog-1', title: 'Lower Limb Quadriceps Fortification', status: 'Active', progressPercent: 75, completedSessions: 14, totalSessions: 20, frequency: '3x Weekly' },
      { id: 'prog-2', title: 'Proprioception & Core Balance', status: 'Active', progressPercent: 50, completedSessions: 5, totalSessions: 10, frequency: '2x Weekly' },
    ],
    exercises: [
      { id: 'ex-1', name: 'Straight Leg Raises with 2kg Ankle Weight', sets: 3, reps: 15, frequency: 'Daily', targetArea: 'Quadriceps', status: 'assigned' },
      { id: 'ex-2', name: 'Terminal Knee Extension (TKE) with Band', sets: 4, reps: 20, frequency: 'Daily', targetArea: 'VMO', status: 'completed' },
    ],
    clinicalNotes: [
      { id: 'cn-1', text: 'Patient reports mild tightness after 20-min treadmill walk. Added hamstring stretching.', date: 'Aug 08, 2026', doctorName: 'Dr. Ananya Sharma', category: 'clinical' },
    ],
  },
  {
    patientId: '#OM-4190',
    name: 'Rajesh Kumar',
    age: 44,
    gender: 'Male',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    condition: 'Chronic Pain',
    therapistName: 'Dr. Rohan Kapoor',
    therapistInitials: 'RK',
    therapistAvatarBg: 'bg-purple-50 text-purple-700',
    therapistSpecialization: 'Spinal Rehabilitation',
    nextAppointmentDate: 'Tomorrow',
    nextAppointmentTime: '11:00 AM',
    recoveryScore: 64,
    status: 'Active Treatment',
    phone: '+91 98765 22222',
    email: 'rajesh.k@example.com',
    joinedDate: 'May 02, 2026',
    address: 'H-12, Sector 15, Noida',
    bloodGroup: 'B+',
    emergencyContact: {
      name: 'Sunita Kumar',
      relation: 'Spouse',
      phone: '+91 98765 88888',
    },
    notes: 'L4-L5 herniated disc lumbar stabilization protocol.',
    painLevel: 'Moderate',
    programsAssignedCount: 1,
    sessionsCompleted: 8,
    sessionsTotal: 16,
    treatmentPlan: {
      title: 'Lumbar Core Stabilization',
      subtitle: '6-Week Spine Alignment Program',
      progress: 50,
      frequency: '2x Weekly',
      duration: '6 Weeks',
    },
    medicalHistory: {
      primaryDiagnosis: 'L4-L5 Lumbar Disc Bulge',
      severity: 'Moderate',
      allergies: ['Sulfa drugs'],
      surgeries: ['None'],
      chronicConditions: ['Mild Hypertension'],
      vitals: {
        bloodPressure: '130/85 mmHg',
        heartRate: '78 bpm',
        height: '172 cm',
        weight: '82 kg',
        bmi: '27.7',
      },
    },
    goals: [
      { id: 'g-10', text: 'Sit for > 45 minutes without lumbar radiation pain', category: 'SHORT TERM', completed: false },
    ],
    reports: [
      { id: 'rep-10', title: 'Lumbar Spine MRI Report', date: 'May 01, 2026', size: '3.1 MB', type: 'mri' },
    ],
    upcomingAppointments: [
      { id: 'apt-10', date: 'Tomorrow', time: '11:00 AM', doctorName: 'Dr. Rohan Kapoor', type: 'Spine Decompression Therapy', status: 'upcoming' },
    ],
    pastAppointments: [
      { id: 'apt-11', date: 'Aug 04, 2026', time: '11:00 AM', doctorName: 'Dr. Rohan Kapoor', type: 'Lumbar Traction Session', status: 'completed' },
    ],
    payments: [
      { id: 'pay-10', date: 'May 02, 2026', amount: 5000, method: 'Credit Card', status: 'paid', invoiceNumber: 'INV-2026-012', description: 'Lumbar Therapy Package' },
      { id: 'pay-11', date: 'Aug 10, 2026', amount: 2000, method: 'Pending', status: 'pending', invoiceNumber: 'INV-2026-095', description: 'Physio Session Renewal' },
    ],
    programs: [
      { id: 'prog-10', title: 'Lumbar Spine Core Stabilization', status: 'Active', progressPercent: 50, completedSessions: 8, totalSessions: 16, frequency: '2x Weekly' },
    ],
    exercises: [
      { id: 'ex-10', name: 'Bird-Dog Lumbar Extension', sets: 3, reps: 10, frequency: 'Daily', targetArea: 'Core / Erector Spinae', status: 'assigned' },
      { id: 'ex-11', name: 'Pelvic Tilts & Cat-Camel Stretch', sets: 3, reps: 12, frequency: 'Daily', targetArea: 'Lower Back Flexibility', status: 'completed' },
    ],
    clinicalNotes: [
      { id: 'cn-10', text: 'Patient reports mild lumbar fatigue during long driving. Recommended lumbar cushion support.', date: 'Aug 04, 2026', doctorName: 'Dr. Rohan Kapoor', category: 'clinical' },
    ],
  },
  {
    patientId: '#OM-9021',
    name: 'Sunita Sharma',
    age: 52,
    gender: 'Female',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    condition: 'Orthopedic',
    therapistName: 'Dr. Ananya Sharma',
    therapistInitials: 'AS',
    therapistAvatarBg: 'bg-teal-50 text-teal-700',
    therapistSpecialization: 'Orthopedic & Joint Mobilization',
    nextAppointmentDate: 'Aug 20',
    nextAppointmentTime: '02:00 PM',
    recoveryScore: 92,
    status: 'Recovered',
    phone: '+91 98765 33333',
    email: 'sunita.sharma@example.com',
    joinedDate: 'Apr 10, 2026',
    address: 'C-88, Vasant Vihar, New Delhi',
    bloodGroup: 'A+',
    emergencyContact: {
      name: 'Vikas Sharma',
      relation: 'Son',
      phone: '+91 98765 77777',
    },
    notes: 'Frozen shoulder stage 3 complete recovery. Maintenance exercises advised.',
    painLevel: 'Mild',
    programsAssignedCount: 2,
    sessionsCompleted: 24,
    sessionsTotal: 24,
    treatmentPlan: {
      title: 'Adhesive Capsulitis (Frozen Shoulder) Protocol',
      subtitle: 'Complete Glenohumeral Range Restoration',
      progress: 100,
      frequency: 'Completed',
      duration: '16 Weeks',
    },
    medicalHistory: {
      primaryDiagnosis: 'Right Adhesive Capsulitis',
      severity: 'Mild',
      allergies: ['None'],
      surgeries: ['None'],
      chronicConditions: ['Type 2 Diabetes'],
      vitals: {
        bloodPressure: '124/82 mmHg',
        heartRate: '70 bpm',
        height: '160 cm',
        weight: '65 kg',
        bmi: '25.4',
      },
    },
    goals: [
      { id: 'g-20', text: 'Reach 170° overhead shoulder abduction', category: 'LONG TERM', completed: true },
    ],
    reports: [
      { id: 'rep-20', title: 'Shoulder Range of Motion Discharge Certificate', date: 'Aug 01, 2026', size: '1.2 MB', type: 'pdf' },
    ],
    upcomingAppointments: [
      { id: 'apt-20', date: 'Aug 20', time: '02:00 PM', doctorName: 'Dr. Ananya Sharma', type: 'Monthly Follow-up Check', status: 'upcoming' },
    ],
    pastAppointments: [
      { id: 'apt-21', date: 'Aug 01, 2026', time: '02:00 PM', doctorName: 'Dr. Ananya Sharma', type: 'Final Discharge Assessment', status: 'completed' },
    ],
    payments: [
      { id: 'pay-20', date: 'Apr 10, 2026', amount: 8000, method: 'Bank Transfer', status: 'paid', invoiceNumber: 'INV-2026-004', description: 'Full Shoulder Rehab Package' },
    ],
    programs: [
      { id: 'prog-20', title: 'Shoulder Rotator Mobilization', status: 'Completed', progressPercent: 100, completedSessions: 24, totalSessions: 24, frequency: '3x Weekly' },
    ],
    exercises: [
      { id: 'ex-20', name: 'Pendulum Shoulder Swings & Wand Exercises', sets: 3, reps: 15, frequency: 'Maintenance', targetArea: 'Glenohumeral Joint', status: 'completed' },
    ],
    clinicalNotes: [
      { id: 'cn-20', text: 'Full range of motion achieved. Discharged with maintenance exercise routine.', date: 'Aug 01, 2026', doctorName: 'Dr. Ananya Sharma', category: 'clinical' },
    ],
  },
  {
    patientId: '#OM-7734',
    name: 'Amit Patel',
    age: 36,
    gender: 'Male',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    condition: 'ACL Recovery',
    therapistName: 'Dr. Dev Mukherjee',
    therapistInitials: 'DM',
    therapistAvatarBg: 'bg-sky-50 text-sky-700',
    therapistSpecialization: 'Sports Injuries & Agility Rehab',
    nextAppointmentDate: 'Aug 15',
    nextAppointmentTime: '09:30 AM',
    recoveryScore: 78,
    status: 'Active Treatment',
    phone: '+91 98765 44444',
    email: 'amit.patel@example.com',
    joinedDate: 'Jul 01, 2026',
    address: '401, Sapphire Heights, Ahmedabad',
    bloodGroup: 'O-',
    emergencyContact: {
      name: 'Kavita Patel',
      relation: 'Spouse',
      phone: '+91 98765 66611',
    },
    notes: 'Sports agility & plyometric conditioning phase starting this week.',
    painLevel: 'Mild',
    programsAssignedCount: 1,
    sessionsCompleted: 10,
    sessionsTotal: 18,
    treatmentPlan: {
      title: 'Sports ACL Conditioning & Return to Sport',
      subtitle: 'Advanced Agility and Dynamic Balance',
      progress: 55,
      frequency: '3x Weekly',
      duration: '10 Weeks',
    },
    medicalHistory: {
      primaryDiagnosis: 'Left ACL Sprain & Meniscus Tear',
      severity: 'Moderate',
      allergies: ['None'],
      surgeries: ['Arthroscopic Knee Debridement'],
      chronicConditions: ['None'],
      vitals: {
        bloodPressure: '118/76 mmHg',
        heartRate: '68 bpm',
        height: '182 cm',
        weight: '79 kg',
        bmi: '23.8',
      },
    },
    goals: [
      { id: 'g-30', text: 'Complete shuttle run drills at 80% effort', category: 'LONG TERM', completed: false },
    ],
    reports: [
      { id: 'rep-30', title: 'Dynamic Isokinetic Strength Assessment', date: 'Jul 28, 2026', size: '1.9 MB', type: 'pdf' },
    ],
    upcomingAppointments: [
      { id: 'apt-30', date: 'Aug 15', time: '09:30 AM', doctorName: 'Dr. Dev Mukherjee', type: 'Agility & Plyometrics Drill', status: 'upcoming' },
    ],
    pastAppointments: [
      { id: 'apt-31', date: 'Aug 08, 2026', time: '09:30 AM', doctorName: 'Dr. Dev Mukherjee', type: 'Single Leg Hop Assessment', status: 'completed' },
    ],
    payments: [
      { id: 'pay-30', date: 'Jul 01, 2026', amount: 4500, method: 'Credit Card', status: 'paid', invoiceNumber: 'INV-2026-056', description: 'Sports Physio Program Phase 1' },
    ],
    programs: [
      { id: 'prog-30', title: 'Plyometric Agility & Quad Balance', status: 'Active', progressPercent: 55, completedSessions: 10, totalSessions: 18, frequency: '3x Weekly' },
    ],
    exercises: [
      { id: 'ex-30', name: 'Box Jumps & Lateral Skater Hops', sets: 3, reps: 12, frequency: '3x Weekly', targetArea: 'Lower Limb Agility', status: 'assigned' },
    ],
    clinicalNotes: [
      { id: 'cn-30', text: 'Good quad symmetry observed during hop tests. Cleared for light jogging.', date: 'Aug 08, 2026', doctorName: 'Dr. Dev Mukherjee', category: 'clinical' },
    ],
  },
  {
    patientId: '#OM-3312',
    name: 'Priya Singh',
    age: 29,
    gender: 'Female',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    condition: 'Neuropathy',
    therapistName: 'Dr. Rohan Kapoor',
    therapistInitials: 'RK',
    therapistAvatarBg: 'bg-purple-50 text-purple-700',
    therapistSpecialization: 'Neurological Rehabilitation',
    nextAppointmentDate: 'Aug 16',
    nextAppointmentTime: '03:15 PM',
    recoveryScore: 55,
    status: 'Observation',
    phone: '+91 98765 55555',
    email: 'priya.singh@example.com',
    joinedDate: 'Jul 15, 2026',
    address: 'E-55, Phase 2, Mohali',
    bloodGroup: 'AB+',
    emergencyContact: {
      name: 'Deepak Singh',
      relation: 'Brother',
      phone: '+91 98765 44332',
    },
    notes: 'Peripheral neuropathy sensory re-education and neuro-dynamics.',
    painLevel: 'Moderate',
    programsAssignedCount: 1,
    sessionsCompleted: 5,
    sessionsTotal: 12,
    treatmentPlan: {
      title: 'Neuro-Dynamic Gliding Protocol',
      subtitle: 'Upper Limb Nerve Conduction & Desensitization',
      progress: 40,
      frequency: '2x Weekly',
      duration: '6 Weeks',
    },
    medicalHistory: {
      primaryDiagnosis: 'Cervical Radiculopathy & Peripheral Neuropathy',
      severity: 'Moderate',
      allergies: ['NSAIDs'],
      surgeries: ['None'],
      chronicConditions: ['None'],
      vitals: {
        bloodPressure: '116/74 mmHg',
        heartRate: '75 bpm',
        height: '165 cm',
        weight: '58 kg',
        bmi: '21.3',
      },
    },
    goals: [
      { id: 'g-40', text: 'Reduce hand tingling sensation during typing', category: 'SHORT TERM', completed: false },
    ],
    reports: [
      { id: 'rep-40', title: 'Nerve Conduction Velocity (NCV) Study', date: 'Jul 10, 2026', size: '2.8 MB', type: 'pdf' },
    ],
    upcomingAppointments: [
      { id: 'apt-40', date: 'Aug 16', time: '03:15 PM', doctorName: 'Dr. Rohan Kapoor', type: 'Median Nerve Mobilization', status: 'upcoming' },
    ],
    pastAppointments: [
      { id: 'apt-41', date: 'Aug 09, 2026', time: '03:15 PM', doctorName: 'Dr. Rohan Kapoor', type: 'Sensory Re-education Session', status: 'completed' },
    ],
    payments: [
      { id: 'pay-40', date: 'Jul 15, 2026', amount: 3000, method: 'Cash', status: 'paid', invoiceNumber: 'INV-2026-077', description: 'Neuro Rehab Starter Session' },
    ],
    programs: [
      { id: 'prog-40', title: 'Median & Ulnar Nerve Gliding', status: 'Active', progressPercent: 40, completedSessions: 5, totalSessions: 12, frequency: '2x Weekly' },
    ],
    exercises: [
      { id: 'ex-40', name: 'Cervical Nerve Flossing & Wrist Extension Glides', sets: 3, reps: 10, frequency: 'Daily', targetArea: 'Upper Extremity Nerves', status: 'assigned' },
    ],
    clinicalNotes: [
      { id: 'cn-40', text: 'Tingling in right index finger reduced after nerve flossing drills.', date: 'Aug 09, 2026', doctorName: 'Dr. Rohan Kapoor', category: 'clinical' },
    ],
  },
  {
    patientId: '#OM-6102',
    name: 'Vikramaditya Sen',
    age: 41,
    gender: 'Male',
    avatarUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150&auto=format&fit=crop&q=80',
    condition: 'Rehab',
    therapistName: 'Dr. Dev Mukherjee',
    therapistInitials: 'DM',
    therapistAvatarBg: 'bg-sky-50 text-sky-700',
    therapistSpecialization: 'Shoulder & Upper Extremity Specialist',
    nextAppointmentDate: 'Aug 18',
    nextAppointmentTime: '01:00 PM',
    recoveryScore: 82,
    status: 'Active Treatment',
    phone: '+91 98765 66666',
    email: 'vikram.sen@example.com',
    joinedDate: 'Jun 22, 2026',
    address: 'Flat 12B, Salt Lake, Kolkata',
    bloodGroup: 'A-',
    emergencyContact: {
      name: 'Meera Sen',
      relation: 'Spouse',
      phone: '+91 98765 11223',
    },
    notes: 'Rotator cuff tear non-operative rehabilitation.',
    painLevel: 'Mild',
    programsAssignedCount: 2,
    sessionsCompleted: 12,
    sessionsTotal: 15,
    treatmentPlan: {
      title: 'Rotator Cuff Conservative Strengthening',
      subtitle: 'Supraspinatus & Scapular Dyskinesis Program',
      progress: 75,
      frequency: '2x Weekly',
      duration: '8 Weeks',
    },
    medicalHistory: {
      primaryDiagnosis: 'Partial Thickness Supraspinatus Tear',
      severity: 'Mild',
      allergies: ['None'],
      surgeries: ['None'],
      chronicConditions: ['None'],
      vitals: {
        bloodPressure: '122/78 mmHg',
        heartRate: '72 bpm',
        height: '175 cm',
        weight: '76 kg',
        bmi: '24.8',
      },
    },
    goals: [
      { id: 'g-50', text: 'Overhead shoulder elevation above 150° without pain', category: 'SHORT TERM', completed: true },
    ],
    reports: [
      { id: 'rep-50', title: 'Right Shoulder MRI Scan', date: 'Jun 18, 2026', size: '3.4 MB', type: 'mri' },
    ],
    upcomingAppointments: [
      { id: 'apt-50', date: 'Aug 18', time: '01:00 PM', doctorName: 'Dr. Dev Mukherjee', type: 'Scapular Stability Check', status: 'upcoming' },
    ],
    pastAppointments: [
      { id: 'apt-51', date: 'Aug 11, 2026', time: '01:00 PM', doctorName: 'Dr. Dev Mukherjee', type: 'Theraband Resistance Progression', status: 'completed' },
    ],
    payments: [
      { id: 'pay-50', date: 'Jun 22, 2026', amount: 4000, method: 'Net Banking', status: 'paid', invoiceNumber: 'INV-2026-039', description: 'Rotator Cuff Rehab Program' },
    ],
    programs: [
      { id: 'prog-50', title: 'Scapular Setting & External Rotators', status: 'Active', progressPercent: 75, completedSessions: 12, totalSessions: 15, frequency: '2x Weekly' },
    ],
    exercises: [
      { id: 'ex-50', name: 'Sidelying External Rotation with 2kg Dumbbell', sets: 3, reps: 15, frequency: 'Daily', targetArea: 'Infraspinatus & Teres Minor', status: 'completed' },
    ],
    clinicalNotes: [
      { id: 'cn-50', text: 'Scapular dyskinesis significantly improved. Patient reports 0 pain during daily driving.', date: 'Aug 11, 2026', doctorName: 'Dr. Dev Mukherjee', category: 'clinical' },
    ],
  },
];
