export const Strings = {
  brand: {
    name: 'ONE MEDICAL',
    tagline: 'PHYSIOTHERAPY & RECOVERY',
    footer: 'Powered by One Medical Care',
  },
  welcome: {
    title: 'Recover Better. Move Stronger.',
    subtitle:
      'Book appointments, follow personalized recovery programs, complete daily exercises and track your progress all in one app.',
    getStarted: 'Get Started',
    alreadyHaveAccount: 'Already have an account? ',
    signIn: 'Sign In',
  },
  accessibility: {
    brandLogo: 'One Medical Logo',
    getStartedButton: 'Get Started button',
    signInButton: 'Sign into existing account link',
    heroImage: 'Physiotherapist assisting patient during a stretch session',
    backButton: 'Go back to previous screen',
    countrySelector: 'Country code selector',
    phoneInput: 'Mobile phone number input field',
    continueButton: 'Continue login process',
    termsLink: 'Terms of service link',
    privacyLink: 'Privacy policy link',
    needHelpButton: 'Need help support button',
    editNumberButton: 'Edit mobile phone number link',
    resendCodeButton: 'Resend verification code button',
    avatarPicker: 'Upload or change profile picture',
    fullNameInput: 'Full name input field',
    dobInput: 'Date of birth input field',
    genderMaleButton: 'Select Male gender option',
    genderFemaleButton: 'Select Female gender option',
    heightInput: 'Height in centimeters input field',
    weightInput: 'Weight in kilograms input field',
  },
  login: {
    title: 'Welcome Back 👋',
    subtitle: 'Enter your mobile number to continue your recovery journey.',
    placeholder: 'Enter your mobile number',
    continue: 'Continue',
    termsPrefix: 'By continuing you agree to the ',
    termsOfService: 'Terms of Service',
    and: ' and ',
    privacyPolicy: 'Privacy Policy',
    needHelp: 'Need Help?',
    searchCountry: 'Search country or dial code...',
    selectCountry: 'Select Country',
    closeModal: 'Close country selection modal',
  },
  otp: {
    title: 'Verify Your Number',
    subtitlePrefix: "We've sent a 6-digit verification code to",
    editNumber: 'Edit Number',
    continue: 'Continue',
    resendIn: 'Resend in',
    resendCode: 'Resend Code',
    needHelp: 'Need Help?',
  },
  profile: {
    title: 'Complete Your Profile',
    subtitle: 'Help us personalize your recovery journey.',
    avatarTitle: "Let's get to know you",
    avatarSubtitle: "We'll personalize your recovery journey\nin less than a minute.",
    sectionPersonalDetails: 'PERSONAL DETAILS',
    fullNameLabel: 'Full Name',
    fullNamePlaceholder: 'Enter your Name',
    dobLabel: 'Date of Birth',
    dobPlaceholder: 'mm/dd/yyyy',
    genderLabel: 'Gender',
    genderMale: 'Male',
    genderFemale: 'Female',
    sectionBodyMeasurements: 'BODY MEASUREMENTS',
    heightLabel: 'Height (cm)',
    weightLabel: 'Weight (kg)',
    sectionPrimaryConcern: 'PRIMARY CONCERN',
    continue: 'Continue',
    validationNameRequired: 'Please enter your full name',
    validationDobRequired: 'Please enter a valid date of birth',
    validationConcernRequired: 'Please select your primary concern',
    successTitle: 'Profile Completed!',
    successMessage: 'Your recovery profile has been saved successfully.',
    concerns: [
      {
        id: 'back_pain',
        title: 'Back Pain',
        subtitle: 'Lumbar & spine relief',
        icon: 'medical-outline',
      },
      {
        id: 'sports_injury',
        title: 'Sports Injury',
        subtitle: 'Get back to the field',
        icon: 'fitness-outline',
      },
      {
        id: 'knee_pain',
        title: 'Knee Pain',
        subtitle: 'Joint stability training',
        icon: 'body-outline',
      },
      {
        id: 'foot_pain',
        title: 'Foot Pain',
        subtitle: 'Plantar & ankle care',
        icon: 'footsteps-outline',
      },
      {
        id: 'mobility',
        title: 'Mobility',
        subtitle: 'Range of motion improvement',
        icon: 'accessibility-outline',
      },
      {
        id: 'other',
        title: 'Other',
        subtitle: 'Customized approach',
        icon: 'sparkles-outline',
      },
    ],
  },
  enableExperience: {
    title: 'Enable Your Experience',
    subtitle: "Choose the features you'd like to use. You can change these anytime in Settings.",
    continue: 'Continue',
    skipForNow: 'Skip for Now',
    enableButton: 'Enable',
    enabledButton: 'Enabled',
    features: [
      {
        id: 'reminders',
        title: 'Appointment Reminders',
        subtitle: 'Never miss upcoming appointments.',
        icon: 'notifications-outline',
        badgeBg: '#EFF6FF',
        iconColor: '#2563EB',
      },
      {
        id: 'clinics',
        title: 'Nearby Clinics',
        subtitle: 'Find physiotherapists and clinics near your location.',
        icon: 'location-outline',
        badgeBg: '#E0F2FE',
        iconColor: '#0284C7',
      },
      {
        id: 'progress',
        title: 'Recovery Progress',
        subtitle: 'Upload photos to track your rehabilitation journey.',
        icon: 'camera-outline',
        badgeBg: '#F3E8FF',
        iconColor: '#9333EA',
      },
    ],
  },
  completion: {
    title: "You're All Set! 🎉",
    subtitle: 'Your profile is ready. Book appointments, follow recovery programs and track your progress with ONE MEDICAL.',
    explore: 'Explore ONE MEDICAL',
    maybeLater: 'Maybe Later',
  },
  sessionComplete: {
    title: 'Session Complete! 🎉',
    subtitle: "Amazing work! You've completed today's recovery session.",
    exercisesLabel: 'EXERCISES',
    exercisesValue: '5 of 5',
    durationLabel: 'DURATION',
    durationValue: '22 Minutes',
    streakLabel: 'STREAK',
    streakValue: '8 Days',
    recoveryLabel: 'RECOVERY',
    recoveryValue: '72%',
    recoveryBadge: '+2% Today',
    newAchievementsTitle: 'NEW ACHIEVEMENTS',
    achievements: [
      { id: 'streak', icon: '🔥', title: '7-Day Streak' },
      { id: 'master', icon: '🏆', title: 'Session Master' },
      { id: 'milestone', icon: '💪', title: 'Recovery Milestone' },
    ],
    therapistNoteTitle: 'Note from Therapist',
    therapistNoteText:
      "Excellent work today! Remember to stay hydrated and continue with tomorrow's session.",
    backToDashboardBtn: 'Back to Recovery Dashboard',
    viewProgressBtn: 'View Recovery Progress',
  },
  explore: {
    greeting: 'Good Morning, Sagar 👋',
    userNameDefault: 'Sagar',
    subtitle: "Let's continue your recovery journey.",
    searchPlaceholder: 'Search therapists, clinics or treatments',
    appointment: {
      headerTag: "TODAY'S APPOINTMENT",
      dateTag: 'Oct 24',
      time: '10:30 AM',
      doctorName: 'Dr. Sarah Johnson',
      specialty: 'Orthopedic Physiotherapist',
      clinic: 'ONE MEDICAL Clinic, Hyderabad',
      viewDetails: 'View Details',
      getDirections: 'Get Directions',
    },
    recovery: {
      title: 'Your Recovery',
      subtitle: 'Keep up the great progress!',
      overallScore: 72,
      scoreLabel: 'Recovery Score 72%',
      trendLabel: 'Improving steadily',
      trendTag: '+8% this week',
      weekTag: 'Week 4 of Recovery',
      quote: "“You're making excellent progress.”",
    },
    exercises: {
      title: "Today's Exercises",
      duration: '18 Minutes total',
      remaining: '3 of 5',
      remainingLabel: 'Remaining',
      progress: 0.4,
      startSession: "Start Today's Session",
      items: [
        {
          id: 'ex_1',
          name: 'Hamstring Stretch',
          duration: '5 Minutes',
          completed: false,
        },
        {
          id: 'ex_2',
          name: 'Pelvic Tilts',
          duration: '8 Minutes',
          completed: true,
        },
        {
          id: 'ex_3',
          name: 'Cat-Cow Stretch',
          duration: '5 Minutes',
          completed: false,
        },
      ],
    },
    quickActions: [
      {
        id: 'book',
        title: 'Book Appointment',
        description: 'Find available time slots.',
        icon: 'calendar-outline',
        bgColor: '#EBF5FF',
        iconColor: '#0284C7',
      },
      {
        id: 'find',
        title: 'Find Physiotherapist',
        description: 'Browse specialists near you.',
        icon: 'medical-outline',
        bgColor: '#E6F7F5',
        iconColor: '#0D9488',
      },
      {
        id: 'reports',
        title: 'Medical Reports',
        description: 'View your reports.',
        icon: 'document-text-outline',
        bgColor: '#F5EEFF',
        iconColor: '#9333EA',
      },
      {
        id: 'payments',
        title: 'Payments',
        description: 'Invoices & history.',
        icon: 'card-outline',
        bgColor: '#EAF8F0',
        iconColor: '#16A34A',
      },
    ],
    recommendedPhysio: {
      title: 'Recommended Physiotherapists',
      viewAll: 'View All',
      doctors: [
        {
          id: 'doc_ananya',
          name: 'Dr. Ananya Iyer',
          title: 'Senior MSK Specialist',
          info: '12+ Years Exp  •  2.4 km away',
          rating: 4.9,
          availableToday: true,
          imageName: 'doctor_ananya',
        },
        {
          id: 'doc_arjun',
          name: 'Dr. Arjun Mehta',
          title: 'Sports Rehab Specialist',
          info: '10+ Years Exp  •  3.1 km away',
          rating: 4.8,
          availableToday: false,
          imageName: 'doctor_arjun',
        },
      ],
    },
    recoveryTip: {
      title: "Today's Recovery Tip",
      tip: 'Stretch for 5 minutes before starting today\'s exercises to improve flexibility and reduce muscle stiffness.',
      tag: 'RECOMMENDED BY YOUR PHYSIOTHERAPIST',
    },
    upcomingActivity: {
      title: 'Upcoming Activity',
      viewSchedule: 'View Schedule',
      items: [
        {
          id: 'act_1',
          time: '6:00 PM',
          day: 'TODAY',
          title: 'Exercise Session',
          subtitle: 'Core & Mobility Routine',
          icon: 'fitness-outline',
        },
        {
          id: 'act_2',
          time: '9:30 AM',
          day: 'TOMORROW',
          title: 'Follow-up Appointment',
          subtitle: 'Dr. Sarah Mitchell',
          icon: 'calendar-outline',
        },
      ],
    },
    assistance: {
      title: 'Need assistance?',
      subtitle: 'Our care team is here to help you with your recovery journey.',
      contactSupport: 'Contact Support',
      faq: 'Frequently Asked Questions',
    },
    sections: {
      stats: 'YOUR RECOVERY SUMMARY',
      categories: 'CATEGORIES',
      programs: 'ACTIVE RECOVERY PROGRAMS',
      specialists: 'TOP PHYSIOTHERAPISTS',
      nearbyClinics: 'NEARBY CLINICS',
    },
    stats: {
      streakTitle: 'Current Streak',
      streakValue: '5 Days 🔥',
      completedTitle: 'Sessions Completed',
      completedValue: '12 / 16',
      nextAppointmentTitle: 'Next Session Today',
      nextAppointmentTime: '4:30 PM with Dr. Sarah',
    },
    categories: [
      { id: 'all', label: 'All', icon: 'grid-outline' },
      { id: 'knee', label: 'Knee Pain', icon: 'body-outline' },
      { id: 'back', label: 'Back Pain', icon: 'medical-outline' },
      { id: 'shoulder', label: 'Shoulder', icon: 'fitness-outline' },
      { id: 'mobility', label: 'Mobility', icon: 'accessibility-outline' },
      { id: 'sports', label: 'Sports Rehab', icon: 'trophy-outline' },
    ],
    emptyState: {
      title: 'No Results Found',
      subtitle: 'We couldn’t find matching programs or specialists for your search query.',
      resetButton: 'Reset Search & Filters',
    },
    actions: {
      startSession: 'Start Session',
      bookAppointment: 'Book Visit',
      viewAll: 'View All',
      filter: 'Filter',
      searchClear: 'Clear search input',
    },
    programs: [],
    doctors: [],
    tabs: {
      home: 'Home',
      schedule: 'Schedule',
      recovery: 'Recovery',
      alerts: 'Alerts',
      profile: 'Profile',
    },
  },
  booking: {
    headerTitle: 'Choose Physiotherapist',
    headerSubtitle: 'Select a specialist and time slot for your session',
    searchPlaceholder: 'Search physiotherapists, specialties, or clinics',
    recentlyBookedTitle: 'RECENTLY BOOKED',
    allSpecialistsTitle: 'ALL PHYSIOTHERAPISTS',
    viewAll: 'View All',
    filters: [
      { id: 'all', label: 'All' },
      { id: 'nearby', label: 'Nearby' },
      { id: 'top_rated', label: 'Top Rated' },
      { id: 'available_today', label: 'Available Today' },
      { id: 'online', label: 'Online Consultation' },
      { id: 'exp_10', label: '10+ Years' },
    ],
    placesTitle: 'Select Appointment Place',
    places: [
      {
        id: 'clinic',
        title: 'One Medical Hub',
        subtitle: '4th Floor, Health Tower, Indiranagar, Bengaluru',
        fee: '₹1,500',
        numericFee: 1500,
        icon: 'business-outline',
        badge: 'RECOMMENDED',
      },
      {
        id: 'home',
        title: 'Home Visit',
        subtitle: 'Therapist visits your registered home address',
        fee: '₹2,200',
        numericFee: 2200,
        icon: 'home-outline',
        badge: 'CONVENIENT',
      },
      {
        id: 'online',
        title: 'Video Consultation',
        subtitle: 'HD 1-on-1 virtual assessment session',
        fee: '₹999',
        numericFee: 999,
        icon: 'videocam-outline',
        badge: 'SAVER',
      },
    ],
    dates: [
      { id: 'd1', label: 'TODAY', dateStr: '14 OCT', fullDate: 'Today, Oct 14' },
      { id: 'd2', label: 'TOMORROW', dateStr: '15 OCT', fullDate: 'Tomorrow, Oct 15' },
      { id: 'd3', label: 'THU', dateStr: '16 OCT', fullDate: 'Thursday, Oct 16' },
      { id: 'd4', label: 'FRI', dateStr: '17 OCT', fullDate: 'Friday, Oct 17' },
      { id: 'd5', label: 'SAT', dateStr: '18 OCT', fullDate: 'Saturday, Oct 18' },
    ],
    timeSlots: [
      { id: 't1', time: '10:00 AM', available: true, period: 'morning' },
      { id: 't2', time: '11:30 AM', available: true, period: 'morning' },
      { id: 't3', time: '02:00 PM', available: true, period: 'afternoon' },
      { id: 't4', time: '04:30 PM', available: true, period: 'evening' },
      { id: 't5', time: '05:15 PM', available: true, period: 'evening' },
      { id: 't6', time: '06:00 PM', available: true, period: 'evening' },
    ],
    payment: {
      title: 'Select Payment Method',
      payOnlineTitle: 'Pay Now (Online)',
      payOnlineSubtitle: 'Secure payment via UPI, Cards, or Netbanking.',
      payAtClinicTitle: 'Pay at Clinic',
      payAtClinicSubtitle: 'Complete your payment at the reception after your session.',
      recommendedTag: 'RECOMMENDED',
      methods: [
        {
          id: 'upi',
          name: 'UPI (GPay / PhonePe / Paytm)',
          subtitle: 'Instant & Secure Pay',
          icon: 'qr-code-outline',
        },
        {
          id: 'card',
          name: 'Credit / Debit Card',
          subtitle: 'Visa, Mastercard, RuPay',
          icon: 'card-outline',
        },
        {
          id: 'netbanking',
          name: 'Net Banking',
          subtitle: 'All Indian Banks Supported',
          icon: 'business-outline',
        },
        {
          id: 'wallet',
          name: 'Digital Wallet',
          subtitle: 'PayTM, PhonePe, Amazon Pay',
          icon: 'wallet-outline',
        },
      ],
      summaryTitle: 'Payment Summary',
      consultationFee: 'Consultation Fee',
      serviceTax: 'Service Tax & Platform Fee',
      taxIncluded: 'Included',
      totalAmount: 'Total Amount',
      disclaimer: 'Your payment is encrypted and securely processed using industry-standard protocols.',
      termsText: 'By proceeding, you agree to our Terms of Service and Refund Policy.',
      confirmingTitle: 'Confirming Your Appointment',
      confirmingSub: 'Securely processing your booking & payment...',
      payOnlineBtn: 'Pay & Book Securely',
      payClinicBtn: 'Confirm Appointment',
    },
    confirmation: {
      title: 'Appointment Confirmed 🎉',
      subtitle: "Your appointment has been successfully booked. We've sent the confirmation to your registered mobile number and email.",
      refLabel: 'Booking Reference',
      statusLabel: 'Payment Status',
      statusPaid: 'Paid Online',
      statusPayAtClinic: 'Pending (Pay at Clinic)',
      importantInstructionsTitle: 'IMPORTANT INSTRUCTIONS',
      instructions: [
        'Please arrive 10 minutes prior to your scheduled time.',
        'Carry previous X-rays or medical reports if available.',
        'Wear comfortable, stretchable clothing for physical movement.',
      ],
      addToCalendar: 'Add to Calendar',
      viewAppointments: 'View My Appointments',
      backToHome: 'Back to Home',
    },
    emptyState: {
      title: 'No Physiotherapists Found',
      subtitle: 'No specialists match your current filter or search parameters.',
      resetBtn: 'Clear Filters',
    },
    doctors: [
      {
        id: 'doc_anuj',
        name: 'Dr. Anuj Mehta',
        specialty: 'Sports Rehabilitation Specialist',
        degree: 'Masters in Physiotherapy (MPT), Orthopedics',
        institution: 'AIIMS Delhi',
        rating: 4.9,
        reviewsCount: 128,
        experienceYears: 12,
        experienceStr: '12+ Years Exp.',
        clinicName: 'One Medical Hub',
        clinicAddress: '4th Floor, Health Tower, Indiranagar, Bengaluru',
        distance: '2.4 km',
        fee: '₹1,500',
        numericFee: 1500,
        availableToday: true,
        isTopRated: true,
        isNearby: true,
        supportsOnline: true,
        languages: ['English', 'Hindi', 'Gujarati'],
        imageName: 'doctor_arjun',
        avatarBg: '#E0E7FF',
        bio: 'Specialized in ACL rehabilitation, rotator cuff repairs, and high-performance athletic sports conditioning.',
      },
      {
        id: 'doc_ananya',
        name: 'Dr. Ananya Iyer',
        specialty: 'Senior MSK Specialist',
        degree: 'BPT, MPT (Musculoskeletal Rehabilitation)',
        institution: 'Manipal University',
        rating: 4.9,
        reviewsCount: 154,
        experienceYears: 12,
        experienceStr: '12+ Years Exp.',
        clinicName: 'One Medical Hub',
        clinicAddress: '4th Floor, Health Tower, Indiranagar, Bengaluru',
        distance: '1.8 km',
        fee: '₹1,500',
        numericFee: 1500,
        availableToday: true,
        isTopRated: true,
        isNearby: true,
        supportsOnline: true,
        languages: ['English', 'Hindi', 'Kannada', 'Tamil'],
        imageName: 'doctor_ananya',
        avatarBg: '#F3E8FF',
        bio: 'Expert in spinal alignment, chronic lower back management, and post-operative joint replacement therapy.',
      },
      {
        id: 'doc_sarah',
        name: 'Dr. Sarah Johnson',
        specialty: 'Orthopedic Physiotherapist',
        degree: 'MPT (Orthopedics), Cert. Manual Therapist',
        institution: 'KMC Mangalore',
        rating: 4.8,
        reviewsCount: 96,
        experienceYears: 10,
        experienceStr: '10+ Years Exp.',
        clinicName: 'One Medical Care Clinic',
        clinicAddress: 'Block B, Jubilee Hills, Hyderabad',
        distance: '3.5 km',
        fee: '₹1,400',
        numericFee: 1400,
        availableToday: false,
        isTopRated: true,
        isNearby: false,
        supportsOnline: true,
        languages: ['English', 'Telugu', 'Hindi'],
        imageName: 'care_team_doctor',
        avatarBg: '#DCFCE7',
        bio: 'Focused on posture correction, ergonomic assessment, and non-surgical pain management for desk professionals.',
      },
      {
        id: 'doc_rajesh',
        name: 'Dr. Rajesh Kumar',
        specialty: 'Neuro & Spine Specialist',
        degree: 'MPT (Neurology), DPT',
        institution: 'NIMHANS Bengaluru',
        rating: 4.7,
        reviewsCount: 82,
        experienceYears: 8,
        experienceStr: '8+ Years Exp.',
        clinicName: 'Spine & Neuro Rehab Center',
        clinicAddress: 'Koramangala 5th Block, Bengaluru',
        distance: '4.2 km',
        fee: '₹1,200',
        numericFee: 1200,
        availableToday: true,
        isTopRated: false,
        isNearby: false,
        supportsOnline: false,
        languages: ['English', 'Kannada', 'Hindi'],
        imageName: 'doctor_arjun',
        avatarBg: '#FEF3C7',
        bio: 'Dedicated to neurological rehabilitation, stroke recovery, balance retraining, and chronic sciatica management.',
      },
    ],
  },
  serviceSelection: {
    headerTitle: 'Book Appointment',
    searchPlaceholder: 'Search services or conditions',
    recentlyBookedTitle: 'RECENTLY BOOKED',
    popularServicesTitle: 'POPULAR SERVICES',
    viewAll: 'View All',
    continueButton: 'Continue',
    emptyState: {
      title: 'No Services Found',
      subtitle: 'We couldn’t find any medical services matching your search.',
      resetBtn: 'Clear Search',
    },
    recentlyBooked: [
      {
        id: 'recent_1',
        doctorName: 'Dr. Arjun Mehta',
        specialty: 'Spinal Specialist',
        timeAgo: '2 WEEKS AGO',
        imageName: 'doctor_arjun',
      },
      {
        id: 'recent_2',
        doctorName: 'Dr. Sarah Johnson',
        specialty: 'Sports Specialist',
        timeAgo: '1 MONTH AGO',
        imageName: 'doctor_ananya',
      },
    ],
    services: [
      {
        id: 'back_pain',
        title: 'Back Pain',
        description: 'Relief from chronic or acute spine issues.',
        imageKey: 'service_back_pain',
        category: 'spine',
      },
      {
        id: 'neck_pain',
        title: 'Neck Pain',
        description: 'Correct posture and cervical discomfort.',
        imageKey: 'service_neck_pain',
        category: 'cervical',
      },
      {
        id: 'sports_injury',
        title: 'Sports Injury',
        description: 'Targeted recovery for athletes and active users.',
        imageKey: 'service_sports_injury',
        category: 'sports',
      },
      {
        id: 'post_surgery',
        title: 'Post-Surgery',
        description: 'Guided rehabilitation programs post-operation.',
        imageKey: 'service_post_surgery',
        category: 'rehab',
      },
      {
        id: 'knee_pain',
        title: 'Knee Pain',
        description: 'Joint mobility and strengthening exercises.',
        imageKey: 'service_knee_pain',
        category: 'joint',
      },
      {
        id: 'home_visit',
        title: 'Home Visit',
        description: 'Personalized care delivered at your residence.',
        imageKey: 'service_home_visit',
        category: 'home',
      },
      {
        id: 'online_consult',
        title: 'Online Consult',
        description: 'Speak to an expert',
        imageKey: 'service_online_consult',
        category: 'virtual',
      },
    ],
  },
  therapistDetails: {
    screenTitle: 'Therapist Profile',
    viewDetails: 'View Details',
    bookAppointmentBtn: 'Continue',
    consultationFeeLabel: 'Consultation Fee',
    aboutDoctorTitle: 'About',
    specializationsTitle: 'Specializations',
    educationTitle: 'Education',
    languagesTitle: 'Languages',
    locationTitle: 'Clinic Location',
    nextAvailabilityTitle: 'Next Availability',
    reviewsTitle: 'Patient Reviews',
    verifiedBadge: 'VERIFIED SPECIALIST',
    ratingBadgeText: '4.9 (124 reviews)',
    quote: '"I believe in movement as medicine, focusing on holistic recovery and personalized protocols. My approach combines advanced clinical expertise with deep empathy to help patients regain their freedom of motion."',
    statsGrid: [
      { id: 'patients', value: '12k+', label: 'Patients' },
      { id: 'success', value: '98%', label: 'Success' },
      { id: 'clinics', value: '4', label: 'Clinics' },
      { id: 'qualified', value: 'MPT', label: 'Qualified' },
    ],
    specializations: [
      'Sports Injury',
      'Back Pain',
      'Manual Therapy',
      'Post-Surgery Rehab',
      'Neurological Physiotherapy',
    ],
    education: {
      degree: 'Masters in Physiotherapy (MPT)',
      institution: 'Orthopedics, AIIMS Delhi',
    },
    languages: 'English, Hindi, Kannada',
    clinic: {
      name: 'One Medical Hub',
      address: '4th Floor, Health Tower, Indiranagar, Bengaluru, 560038',
      getDirections: 'Get Directions',
    },
    nextAvailability: [
      {
        dayLabel: 'TODAY, 14 OCT',
        slots: ['04:30 PM', '05:15 PM', '06:00 PM'],
      },
      {
        dayLabel: 'TOMORROW, 15 OCT',
        slots: ['10:00 AM', '11:30 AM', '02:00 PM'],
      },
    ],
    patientReview: {
      name: 'Ananya Kapoor',
      initials: 'AK',
      ratingStr: '4.9 ★',
      avatarBg: '#DBEAFE',
    },
    emptyState: {
      title: 'Therapist Not Found',
      subtitle: 'The selected therapist details could not be loaded. Please return to the list and select a doctor.',
      backBtn: 'Go Back',
    },
  },
  selectDateTime: {
    headerTitle: 'Select Date & Time',
    headerSubtitle: 'Schedule your appointment session',
    placesTitle: 'Select Appointment Place',
    datesTitle: 'Select Date',
    timeSlotsTitle: 'Select Time Slot',
    totalFeeLabel: 'Total Consultation Fee',
    taxesIncluded: 'Taxes Included',
    proceedToPaymentBtn: 'Proceed to Payment',
    emptyState: {
      title: 'No Slots Available',
      subtitle: 'No appointment slots are available for the selected date or location. Please select a different day.',
      resetBtn: 'Select Another Date',
    },
    errorState: {
      title: 'Therapist Details Not Found',
      subtitle: 'Could not load therapist data for booking. Please return and select a valid therapist.',
      backBtn: 'Return to Therapist Details',
    },
  },
  myBookings: {
    headerTitle: 'My Bookings',
    searchPlaceholder: 'Search by therapist, service or status...',
    tabs: {
      all: 'All',
      upcoming: 'Upcoming',
      completed: 'Completed',
      cancelled: 'Cancelled',
    },
    emptyState: {
      title: 'No Bookings Found',
      subtitle: "You don't have any appointments matching this category. Book a session with our top physiotherapists today.",
      bookButton: 'Book Appointment',
    },
    detailsModal: {
      title: 'Booking Details',
      refLabel: 'Booking Reference',
      therapistSectionTitle: 'THERAPIST',
      serviceSectionTitle: 'SERVICE & LOCATION',
      paymentSectionTitle: 'PAYMENT DETAILS',
      instructionsSectionTitle: 'APPOINTMENT INSTRUCTIONS',
      rescheduleBtn: 'Reschedule',
      cancelBtn: 'Cancel Booking',
      getDirectionsBtn: 'Get Directions',
      bookAgainBtn: 'Book Again',
      downloadInvoiceBtn: 'Download Invoice',
      closeBtn: 'Close',
    },
  },
  reschedule: {
    headerTitle: 'Reschedule Appointment',
    headerSubtitle: 'Choose a new date and time slot',
    currentAppointmentTitle: 'CURRENT APPOINTMENT',
    selectNewDateTitle: 'Select New Date',
    selectNewTimeTitle: 'Select New Time Slot',
    reasonTitle: 'Reason for Rescheduling',
    reasonPlaceholder: 'Please tell us why you need to reschedule...',
    policyBanner: 'Free rescheduling allowed up to 2 hours prior to your scheduled time.',
    confirmBtn: 'Confirm Reschedule',
    updatingText: 'Rescheduling your appointment...',
    successTitle: 'Rescheduled Successfully! 🎉',
    successSubtitle: 'Your appointment date & time slot have been updated. We have sent the revised confirmation details.',
    reasons: [
      { id: 'conflict', label: '📅 Schedule Conflict' },
      { id: 'unwell', label: '🤒 Feeling Unwell' },
      { id: 'emergency', label: '🚨 Personal Emergency' },
      { id: 'location', label: '🚗 Travel / Location Issue' },
      { id: 'other', label: '💬 Other Reason' },
    ],
    emptyState: {
      title: 'No Slots Available',
      subtitle: 'No available slots for the selected date. Please choose another date.',
      resetBtn: 'Try Another Date',
    },
  },
  cancelAppointment: {
    headerTitle: 'Cancel Appointment',
    defaultDoctorName: 'Dr. Ananya Iyer',
    defaultDoctorSpecialty: 'MSK Specialist • One Medical Hub',
    defaultOriginalSlot: 'OCT 24, 10:30 AM',
    policyCardTitle: 'Free cancellation until 24 hours before',
    policyCardSubtitle: 'A full refund of ₹1,200 will be credited to your original payment method within 3-5 business days.',
    reasonsTitle: 'Why are you cancelling?',
    reasons: [
      'Feeling Better',
      'Need Another Time',
      'Personal Emergency',
      'Booked by Mistake',
      'Found Another Clinic',
      'Other',
    ],
    rescheduleBoxTitle: 'Need a different time instead?',
    rescheduleBoxSubtitle: 'Keep your care team and simply move the date.',
    rescheduleBtnText: 'Reschedule Appointment',
    cancelBtnText: 'Cancel Appointment',
    keepBtnText: 'Keep Appointment',
    cancelledAlertTitle: 'Appointment Cancelled',
    cancelledAlertMessage: 'Your appointment has been cancelled successfully. Refund will be processed as per policy.',
  },
  appointmentCancelled: {
    title: 'Appointment\nCancelled',
    subtitle: 'Your appointment has been Cancelled successfully. Your Refund Of ₹ 1500 will be procceded within 5 - 7 Days',
    appointmentIdLabel: 'APPOINTMENT ID',
    defaultAppointmentId: '#APT-2024-8842',
    physiotherapistLabel: 'Physiotherapist',
    defaultPhysiotherapist: 'Dr. Ananya Iyer',
    serviceLabel: 'Service',
    defaultService: 'Post-Surgery Rehab',
    clinicLabel: 'Clinic',
    defaultClinic: 'One Medical Hub, MG Road',
    dateTimeLabel: 'Date & Time',
    defaultDate: 'Tue, 17 Sept 2024',
    defaultTime: '09:30 AM (45 mins)',
    modeLabel: 'Mode',
    defaultMode: 'Clinic Visit',
    refundStatusLabel: 'Refund Status',
    defaultRefundStatus: 'Processing',
    bookAppointmentsBtn: 'Book Appointments',
    backToHomeBtn: 'Back to Home',
  },
  recoveryDashboard: {
    greeting: 'Good Morning, Sagar 👋',
    subtitle: "Let's continue today's recovery.",
    banner: {
      improvementBadge: '+8% improvement this week',
      title: 'Week 4 of Recovery',
      description: "Keep going! You're making steady progress toward your full strength.",
      overallScore: '72%',
      overallLabel: 'Overall',
    },
    todaysSession: {
      title: "Today's Session",
      sessionTitle: 'Movement Foundation',
      exercisesCount: '5 Exercises',
      duration: '20 Minutes',
      level: 'Beginner',
      startButton: 'Start Session',
    },
    currentProgram: {
      title: 'Current Program',
      viewProgram: 'View Program >',
      programTitle: 'Lower Back Rehabilitation',
      specialist: 'Specialist: Dr. Ananya Iyer',
      sessionsCompleted: '18 / 24 Sessions',
      progressPercent: '75%',
    },
    achievements: {
      title: 'Achievements',
      items: [
        {
          id: 'streak',
          title: '7 Day Streak',
          iconName: 'flame',
          badgeBg: '#FFEDD5',
          iconColor: '#F97316',
        },
        {
          id: 'sessions',
          title: '25 Sessions',
          iconName: 'ribbon',
          badgeBg: '#E0F2FE',
          iconColor: '#0284C7',
        },
        {
          id: 'milestone',
          title: 'Milestone',
          iconName: 'star',
          badgeBg: '#FEF3C7',
          iconColor: '#F59E0B',
        },
      ],
    },
    weeklyActivity: {
      title: 'Weekly Activity',
      completedLabel: 'Completed',
      pendingLabel: 'Pending',
      days: [
        { day: 'Mon', completedHeight: 80, pendingHeight: 0, status: 'completed' },
        { day: 'Tue', completedHeight: 90, pendingHeight: 0, status: 'completed' },
        { day: 'Wed', completedHeight: 70, pendingHeight: 0, status: 'completed' },
        { day: 'Thu', completedHeight: 85, pendingHeight: 0, status: 'completed' },
        { day: 'Fri', completedHeight: 60, pendingHeight: 25, status: 'partial' },
        { day: 'Sat', completedHeight: 40, pendingHeight: 40, status: 'partial' },
        { day: 'Sun', completedHeight: 0, pendingHeight: 75, status: 'pending' },
      ],
    },
  },
  myRecoveryPrograms: {
    headerTitle: 'My Recovery Programs',
    headerSubtitle: 'Track your rehabilitation journey',
    searchPlaceholder: 'Search recovery programs',
    tabs: ['Active', 'Completed', 'Paused'],
    activeProgram: {
      statusBadge: 'ACTIVE',
      title: 'Lower Back Rehabilitation',
      doctorName: 'Dr. Ananya Iyer',
      sessionsCompletedText: '18 of 24',
      sessionsLabel: 'Sessions Completed',
      progressPercent: '75%',
      recoveryScoreLabel: 'RECOVERY SCORE',
      recoveryScoreVal: '72%',
      improvementNote: 'Showing significant mobility improvement since Week 4',
      continueBtn: 'Continue Program',
      viewDetailsBtn: 'View Details',
    },
    pastProgramsTitle: 'Past Programs',
    pastPrograms: [
      {
        id: 'past_1',
        title: 'Shoulder Mobility',
        dateText: 'Completed Jan 2024',
        status: 'Completed',
        iconName: 'barbell-outline',
        iconBg: '#F3E8FF',
        iconColor: '#9333EA',
        actionText: 'View Summary',
      },
      {
        id: 'past_2',
        title: 'Ankle Stability',
        dateText: 'Completed Nov 2023',
        status: 'Completed',
        iconName: 'walk-outline',
        iconBg: '#E0F2FE',
        iconColor: '#0284C7',
        actionText: 'View Summary',
      },
    ],
    consultBanner: {
      title: 'Need a new plan?',
      subtitle: 'Schedule a consultation with our recovery specialists to start a personalized program tailored to your goals.',
      buttonText: 'Book a Consult',
    },
  },
  recoveryProgramDetails: {
    headerTitle: 'Recovery Program',
    currentProgramBadge: 'CURRENT PROGRAM',
    programTitle: 'Lower Back Rehabilitation',
    doctorName: 'Dr. Ananya Iyer',
    weekProgress: 'Week 2 of 6',
    sessionsProgress: '18 / 24 Sessions',
    anatomical: {
      header: 'Recovery Program',
      title: 'Spine & Lower Back',
      anatomicalFocus: 'Anatomical Focus: Lumbar Region.',
      focusDescription: 'Focus: Strengthening and stabilization exercises for the lower back.',
      viewExercises: 'View Exercises',
    },
    overview: {
      title: 'Program Overview',
      goal: 'Goal: Improve lower back strength and mobility through targeted functional movements.',
      completionLabel: 'Completion',
      completionValue: 'Nov 15, 2024',
      difficultyLabel: 'Difficulty',
      difficultyValue: 'Intermediate',
      frequencyLabel: 'Frequency',
      frequencyValue: '3x per week',
      intensityLabel: 'Intensity',
      intensityValue: 'Progressive',
    },
    todaysSession: {
      title: "Today's Session",
      activeBadge: 'ACTIVE',
      exercisesCount: '5 Exercises',
      duration: '20 Minutes',
      intensity: 'Est. Intensity: Moderate',
      startButton: "Start Today's Session",
    },
    roadmap: {
      title: 'Recovery Roadmap',
      items: [
        {
          id: 'w1',
          title: 'Week 1: Fundamentals',
          description: 'Core activation and basic flexibility work.',
          status: 'completed',
        },
        {
          id: 'w2',
          title: 'Week 2: Mobility Focus',
          description: 'Improving range of motion in the lumbar spine.',
          status: 'in_progress',
          badgeText: 'IN PROGRESS',
        },
        {
          id: 'w3',
          title: 'Weeks 3-5: Strengthening',
          description: 'Advanced core stability and functional loading.',
          status: 'locked',
        },
        {
          id: 'w4',
          title: 'Week 6: Graduation',
          description: 'Final assessment and maintenance planning.',
          status: 'graduation',
        },
      ],
    },
    doctorNote: {
      title: 'Note from Dr. Iyer',
      quote: '"Focus on slow controlled movements and avoid sudden twisting. Breath control is vital today—inhale as you prep, exhale deeply as you move into the rotation."',
      postedTime: 'Posted 2 hours ago',
    },
  },
  todaySessionDetails: {
    headerTitle: "Today's Session",
    sessionSubhead: 'SESSION 8 OF 24',
    sessionTitle: 'Lower Back Recovery',
    metaTime: '20 Minutes',
    metaExercises: '5 Exercises',
    metaLevel: 'Beginner',
    goalTitle: 'The Goal',
    goalDescription: 'Improve flexibility and reduce lower back pain through controlled mobility and core stability movements.',
    requiredEquipmentTitle: 'REQUIRED EQUIPMENT',
    equipment: [
      { id: 'band', label: 'Band', icon: 'barcode-outline' },
      { id: 'mat', label: 'Mat', icon: 'restaurant-outline' },
      { id: 'water', label: 'Water', icon: 'water-outline' },
    ],
    exercisesTitle: 'Exercises',
    completionProgress: '1/5 Complete',
    exercisesList: [
      {
        id: 'ex_1',
        name: 'Pelvic Tilt',
        reps: '8 reps • Active',
        status: 'active',
      },
      {
        id: 'ex_2',
        name: 'Cat-Cow Stretch',
        reps: '1 min • Locked',
        status: 'locked',
      },
      {
        id: 'ex_3',
        name: 'Bird Dog',
        reps: '10 reps • Locked',
        status: 'locked',
      },
      {
        id: 'ex_4',
        name: 'Bridge',
        reps: '12 reps • Locked',
        status: 'locked',
      },
      {
        id: 'ex_5',
        name: "Child's Pose",
        reps: '2 mins • Locked',
        status: 'locked',
      },
    ],
    doctorTip: {
      quote: '"Take your time and focus on proper form rather than speed."',
      author: '— Dr. Ananya Iyer',
    },
    startSessionBtn: 'Start Session',
  },
  exerciseDetails: {
    headerTitle: 'Excercise Details',
    levelBadge: 'Beginner',
    exerciseTitle: 'Pelvic Tilt',
    metrics: {
      targetAreaLabel: 'Target Area',
      targetAreaValue: 'Lower Back',
      equipmentLabel: 'Equipment',
      equipmentValue: 'Yoga Mat',
      durationLabel: 'Duration',
      durationValue: '2 Minutes',
      repetitionsLabel: 'Repetitions',
      repetitionsValue: '12 Reps × 3',
    },
    instructionsTitle: 'Instructions',
    instructionsList: [
      'Lie flat on your back with knees bent.',
      'Tighten your abdominal muscles.',
      'Gently tilt your pelvis upward.',
      'Hold for 5 seconds.',
      'Return slowly.',
    ],
    clinicalTipsTitle: 'Clinical Tips',
    clinicalTipsList: [
      'Breathe normally',
      'Move slowly',
      'Avoid jerky movements',
      'Stop if you feel sharp pain',
    ],
    mistakesTitle: 'Mistakes to Avoid',
    mistakesList: [
      {
        id: 'mistake_1',
        title: 'Arching your back too much',
        description: 'Keep your spine in a natural neutral alignment. Avoid forcing an artificial curvature that places unnecessary stress on the lower vertebrae.',
      },
      {
        id: 'mistake_2',
        title: 'Holding your breath',
        description: 'Maintain steady, rhythmically paced breathing. Exhale as you engage your abdominals and tilt, and inhale smoothly as you release.',
      },
      {
        id: 'mistake_3',
        title: 'Moving too quickly',
        description: 'Perform each phase with deliberate control. Fast momentum reduces muscle engagement and increases risk of joint strain.',
      },
    ],
    startExerciseBtn: 'Start Exercise',
  },
  activeSession: {
    exerciseProgressTag: 'Exercise 1 of 5',
    title: 'Pelvic Tilt',
    category: 'LOWER BACK',
    setLabel: 'SET 2 OF 3',
    quoteInstruction: '"Breathe normally."',
    markRepCompleteBtn: 'MARK REP COMPLETE',
  },
  recoveryProgress: {
    headerTitle: 'Recovery Progress',
    currentStatusTag: 'CURRENT STATUS',
    scoreTitle: 'Recovery\nScore',
    trendPill: '+10% this month',
    weekSubtitle: 'Week 4 of 6',
    scoreValue: '82',
    scorePercent: '%',
    mobilityTrendTitle: 'Mobility Trend',
    timeFilters: [
      { id: 'week', label: 'Week' },
      { id: 'month', label: 'Month' },
      { id: 'three_months', label: '3 Months' },
    ],
    chartDays: [
      { day: 'Mon', active: false },
      { day: 'Tue', active: false },
      { day: 'Wed', active: false },
      { day: 'Thu', active: false },
      { day: 'Fri', active: false },
      { day: 'Sat', active: false },
      { day: 'Today', active: true },
    ],
    stats: {
      sessionsCount: '24',
      sessionsLabel: 'Sessions',
      streakCount: '8 Days',
      streakLabel: 'Streak',
      totalTimeCount: '12.5h',
      totalTimeLabel: 'Total Time',
      exercisesCount: '120',
      exercisesLabel: 'Exercises',
    },
    milestonesTitle: 'Milestones',
    milestonesList: [
      { id: 'm1', title: '25 Sessions', icon: 'trophy', color: '#B45309', bg: '#FEF3C7', iconBg: '#FDE68A' },
      { id: 'm2', title: '10-Day\nStreak', icon: 'flame', color: '#C2410C', bg: '#FFEDD5', iconBg: '#FED7AA' },
      { id: 'm3', title: 'Halfway', icon: 'star', color: '#1D4ED8', bg: '#EFF6FF', iconBg: '#BFDBFE' },
    ],
    therapistFeedback: {
      doctorName: 'DR. SARAH CHEN • THERAPIST',
      quote: '"You\'re showing excellent stability in your lumbar spine movements. Keep up the consistency!"',
      avatarImage: 'doctor_ananya',
    },
    nextMilestone: {
      title: 'Next Milestone',
      subtitle: 'Complete 2 more sessions to finish Week 4.',
      continueBtn: 'Continue Program',
    },
  },
  notifications: {
    headerTitle: 'Notifications',
    markAllRead: 'Mark All as Read',
    sections: {
      today: 'TODAY',
      yesterday: 'YESTERDAY',
      earlier: 'EARLIER',
    },
    categories: ['All', 'Appointments', 'Recovery', 'Payments', 'System'],
    emptyState: {
      title: 'No Notifications',
      subtitle: 'You have no notifications in this category right now.',
    },
    items: [
      {
        id: 'notif_1',
        title: 'Appointment Reminder',
        timeAgo: '1h ago',
        description: 'Your session with Dr. Mehta starts in 1 hour.',
        section: 'TODAY',
        category: 'Appointments',
        isUnread: true,
        iconName: 'calendar-outline',
        iconColor: '#003D9B',
        iconBgColor: '#EFF6FF',
      },
      {
        id: 'notif_2',
        title: 'Recovery Milestone',
        timeAgo: '2m ago',
        description: "Congratulations! You've reached 80% of your Week 4 goals.",
        section: 'TODAY',
        category: 'Recovery',
        isUnread: true,
        iconName: 'trophy-outline',
        iconColor: '#9333EA',
        iconBgColor: '#F3E8FF',
      },
      {
        id: 'notif_3',
        title: 'New Report',
        timeAgo: '1d ago',
        description: 'Your MRI Lumbar Spine report is now available to view.',
        section: 'YESTERDAY',
        category: 'Recovery',
        isUnread: false,
        iconName: 'document-text-outline',
        iconColor: '#0D9488',
        iconBgColor: '#E6F7F5',
      },
      {
        id: 'notif_4',
        title: 'Payment Success',
        timeAgo: '1d ago',
        description: 'Invoice #INV-9902 for ₹1,500 has been processed.',
        section: 'YESTERDAY',
        category: 'Payments',
        isUnread: false,
        iconName: 'checkmark-circle-outline',
        iconColor: '#16A34A',
        iconBgColor: '#EAF8F0',
      },
      {
        id: 'notif_5',
        title: 'System Update',
        timeAgo: '3d ago',
        description: 'PhysioPro version 2.4 is now live with enhanced tracking.',
        section: 'EARLIER',
        category: 'System',
        isUnread: false,
        iconName: 'settings-outline',
        iconColor: '#003D9B',
        iconBgColor: '#EFF6FF',
      },
    ],
  },
  profileDetails: {
    headerTitle: 'Profile',
    userName: 'Sanya Malhotra',
    userMeta: '28 Years • Member since Oct 2023',
    programName: 'ACL Recovery Program',
    editProfileBtn: 'Edit Profile',
    recoverySnapshot: {
      sectionTitle: 'RECOVERY SNAPSHOT',
      scoreLabel: 'Recovery Score',
      scoreValue: '78%',
      activeStatus: '2 Active',
      nextSessionLabel: 'NEXT SESSION',
      nextSessionValue: 'Tomorrow',
      nextSessionTime: '10:30 AM',
      streakLabel: 'STREAK',
      streakValue: '8 Day Streak',
      viewProgressLink: 'View Recovery Progress',
    },
    quickAccess: {
      sectionTitle: 'QUICK ACCESS',
      items: [
        { id: 'medical_info', title: 'Medical Information', icon: 'id-card-outline' },
        { id: 'medical_reports', title: 'Medical Reports', icon: 'document-text-outline' },
        { id: 'payments_invoices', title: 'Payments & Invoices', icon: 'receipt-outline' },
        { id: 'saved_specialists', title: 'Saved Specialists', icon: 'shield-checkmark-outline' },
      ],
    },
    accountSettings: {
      sectionTitle: 'ACCOUNT SETTINGS',
      items: [
        { id: 'notification_prefs', title: 'Notification Preferences', icon: 'notifications-outline' },
        { id: 'privacy_security', title: 'Privacy & Security', icon: 'lock-closed-outline' },
        { id: 'help_support', title: 'Help & Support', icon: 'help-circle-outline' },
        { id: 'about_one_medical', title: 'About ONE MEDICAL', icon: 'information-circle-outline' },
      ],
    },
    logoutBtn: 'Log Out',
    versionText: 'Version 2.4.0-pro',
  },
  editProfileDetails: {
    headerTitle: 'Profile',
    changePhoto: 'Change Photo',
    sections: {
      personalInfo: 'PERSONAL INFORMATION',
      bodyInfo: 'BODY INFORMATION',
      emergencyContact: 'EMERGENCY CONTACT',
    },
    personalInfo: {
      fullNameLabel: 'Full Name',
      fullNameValue: 'Sanya Malhotra',
      emailLabel: 'Email Address',
      emailValue: 'sanya.m@example.com',
      mobileLabel: 'Mobile Number',
      mobileValue: '+91 98765 43210',
      changeMobileBtn: 'Change',
      dobLabel: 'Date of Birth',
      dobValue: '02/25/1992',
      genderLabel: 'Gender',
      genderValue: 'Female',
    },
    bodyInfo: {
      heightLabel: 'Height (cm)',
      heightValue: '165',
      weightLabel: 'Weight (kg)',
      weightValue: '54',
      bloodGroupLabel: 'Blood Group',
      bloodGroupValue: 'O negative (O-)',
    },
    emergencyContact: {
      nameLabel: 'Contact Name',
      nameValue: 'Rajesh Malhotra',
      relationshipLabel: 'Relationship',
      relationshipValue: 'Father',
      phoneLabel: 'Phone Number',
      phoneValue: '+91 98000 12345',
    },
    deleteProfileBtn: 'Delete My Health Profile',
  },
  medicalInfoDetails: {
    headerTitle: 'Medical Information',
    vitalsOverview: {
      sectionTitle: 'VITALS OVERVIEW',
      bloodGroupLabel: 'Blood Group',
      bloodGroupValue: 'O-',
      heightLabel: 'Height',
      heightValue: '168',
      heightUnit: 'cm',
      weightLabel: 'Weight',
      weightValue: '62',
      weightUnit: 'kg',
      viewEmergencyContactsBtn: 'View Emergency Contacts',
    },
    allergies: {
      sectionTitle: 'Allergies',
      emptyText: 'No known allergies',
      addBtn: 'Add Allergy',
    },
    medicalConditions: {
      sectionTitle: 'Medical Conditions',
      items: [
        { id: '1', name: 'Hypertension' },
        { id: '2', name: 'Arthritis (Mild)' },
      ],
    },
    currentMedications: {
      sectionTitle: 'Current Medications',
      items: [
        { id: 'm1', name: 'Etoricoxib', dosage: '60mg, Once Daily' },
        { id: 'm2', name: 'Pantoprazole', dosage: '40mg, Before Breakfast' },
      ],
      addMedicationBtn: 'Add Medication',
    },
    injuryHistory: {
      sectionTitle: 'Injury History',
      items: [
        { id: 'i1', title: 'ACL Reconstruction', subtitle: '2019 • Fully Recovered', active: true },
        { id: 'i2', title: 'Ankle Sprain', subtitle: '2022 • Occasional Stiffness', active: false },
      ],
    },
    emergencyContact: {
      sectionTitle: 'EMERGENCY CONTACT',
      name: 'Arjun Malhotra',
      relationship: 'Spouse',
      phone: '+91 98765 43210',
      initials: 'AM',
    },
  },
  medicalReportsDetails: {
    headerTitle: 'Medical Reports',
    searchPlaceholder: 'Search reports...',
    categories: ['All', 'Assessment', 'Progress', 'X-Ray', 'Prescription'],
    latestReportSectionTitle: 'LATEST REPORT',
    latestReport: {
      id: 'latest_1',
      badge: 'LATEST',
      title: 'Initial Assessment -\nSanya Malhotra',
      doctor: 'Dr. Ananya Iyer',
      date: '24 Oct 2023',
      fileSize: '2.4 MB',
      viewBtnText: 'View Report',
      category: 'Assessment',
    },
    previousReportsSectionTitle: 'PREVIOUS REPORTS',
    previousReports: [
      {
        id: 'prev_1',
        title: 'MRI Lumbar Spine',
        subtitle: 'Radiology Dept',
        date: '18 Oct 2023',
        category: 'X-Ray',
        iconName: 'document-text-outline',
        iconBg: '#E0F2FE',
        iconColor: '#0284C7',
      },
      {
        id: 'prev_2',
        title: 'Progress Summary\nQ3',
        subtitle: 'Dr. Rahul Sharma',
        date: '15 Oct 2023',
        category: 'Progress',
        iconName: 'bar-chart-outline',
        iconBg: '#F3E8FF',
        iconColor: '#9333EA',
      },
      {
        id: 'prev_3',
        title: 'Prescription Refill',
        subtitle: 'Pharmacy Dept',
        date: '12 Oct 2023',
        category: 'Prescription',
        iconName: 'medkit-outline',
        iconBg: '#FEE2E2',
        iconColor: '#EF4444',
      },
    ],
    footerSecurityText: 'All your medical history and clinical data\nis encrypted and secure.',
  },
  paymentsInvoicesDetails: {
    headerTitle: 'Payments & Invoices',
    totalPaidLabel: 'TOTAL PAID',
    totalPaidValue: '₹42,500',
    outstandingLabel: 'OUTSTANDING',
    outstandingValue: '₹0',
    lastPaymentLabel: 'Last Payment',
    lastPaymentValue: '₹3,500 on 24 Oct',
    downloadTaxSummaryBtn: 'Download Tax Summary',
    filterCategories: ['All', 'Paid', 'Pending', 'Refunded'],
    invoices: [
      {
        id: 'inv_1',
        invoiceNo: '#INV-9902',
        title: 'Physiotherapy Session',
        doctor: 'Dr. Ananya Iyer',
        amount: '₹3,500',
        numericAmount: 3500,
        status: 'PAID',
        date: 'Oct 24, 2023',
        paymentMethod: 'UPI',
        paymentIcon: 'qr-code-outline',
      },
      {
        id: 'inv_2',
        invoiceNo: '#INV-9884',
        title: 'Lower Back Assessment',
        doctor: 'Dr. Rohan Mehta',
        amount: '₹2,800',
        numericAmount: 2800,
        status: 'PENDING',
        date: 'Oct 20, 2023',
        paymentMethod: '•••• 4242',
        paymentIcon: 'card-outline',
        payNowBtnText: 'Pay Now',
      },
      {
        id: 'inv_3',
        invoiceNo: '#INV-9851',
        title: 'Sports Injury Rehab',
        doctor: 'Dr. Ananya Iyer',
        amount: '₹3,500',
        numericAmount: 3500,
        status: 'PAID',
        date: 'Oct 15, 2023',
        paymentMethod: 'UPI',
        paymentIcon: 'qr-code-outline',
      },
      {
        id: 'inv_4',
        invoiceNo: '#INV-9800',
        title: 'Canceled Session',
        doctor: 'Dr. Vikram Singhania',
        amount: '₹3,500',
        numericAmount: 3500,
        status: 'REFUNDED',
        date: 'Oct 10, 2023',
        paymentMethod: 'UPI',
        paymentIcon: 'qr-code-outline',
        statusNote: 'Refund processed',
      },
    ],
  },
  invoiceDetailsScreen: {
    headerTitle: 'Invoice Details',
    paidBadge: 'PAID',
    defaultInvoiceNo: '#INV-9902',
    issuedDatePrefix: 'Issued: ',
    paidDatePrefix: 'Paid: ',
    defaultIssuedDate: 'Oct 24, 2023',
    defaultPaidDate: 'Oct 24, 2023',
    clinicName: 'ONE MEDICAL',
    clinicSubtitle: 'HUB & CENTER',
    defaultClinicAddress: 'One Medical Hub, MG Road, Bangalore',
    defaultGstNo: '29AAAAA0000A1Z5',
    serviceDetailsTitle: 'SERVICE DETAILS',
    patientLabel: 'Patient',
    defaultPatientName: 'Sanya Malhotra',
    appointmentLabel: 'Appointment',
    defaultAppointmentNo: '#APT-1024',
    therapistLabel: 'Therapist',
    defaultTherapistName: 'Dr. Ananya Iyer',
    serviceLabel: 'Service',
    defaultServiceName: 'Lumbar Spine Stabilization',
    financialBreakdownTitle: 'FINANCIAL BREAKDOWN',
    consultationFeeLabel: 'Consultation Fee',
    defaultConsultationFee: '₹1,500.00',
    additionalChargesLabel: 'Additional Charges',
    defaultAdditionalCharges: '₹0.00',
    discountLabel: 'Discount',
    defaultDiscount: '-₹150.00',
    gstLabel: 'GST (18%)',
    defaultGst: '₹243.00',
    totalAmountPaidLabel: 'Total Amount Paid',
    defaultTotalAmountPaid: '₹1,593.00',
    paymentMethodLabel: 'Payment Method',
    defaultPaymentMethod: 'UPI (sanya.m@okhdfc)',
    downloadPdfBtn: 'Download PDF',
    shareBtn: 'Share',
    emailBtn: 'Email',
  },
  savedSpecialistsDetails: {
    headerTitle: 'Saved Specialists',
    searchPlaceholder: 'Search saved specialists',
    categories: ['All', 'Nearby', 'Sports', 'Orthopedic', 'Neurological'],
    specialists: [
      {
        id: 'doc_arjun_mehta',
        doctorId: 'doc_anuj',
        name: 'Dr. Arjun Mehta',
        specialty: 'Sports Physiotherapy',
        rating: 4.9,
        isVerified: true,
        clinic: 'One Medical MG Road',
        experience: '12 yrs exp',
        nextAvailable: 'Next: Tomorrow, 10:30 AM',
        distance: '2.4 km',
        imageName: 'doctor_arjun',
        category: 'Sports',
        isSaved: true,
      },
      {
        id: 'doc_sarah_jenkins',
        doctorId: 'doc_sarah',
        name: 'Dr. Sarah Jenkins',
        specialty: 'Neurological Recovery',
        rating: 5.0,
        isVerified: true,
        clinic: 'One Medical Chelsea',
        experience: '15 yrs exp',
        nextAvailable: 'Next: Mon, 9:00 AM',
        distance: '1.1 km',
        imageName: 'care_team_doctor',
        category: 'Neurological',
        isSaved: true,
      },
      {
        id: 'doc_priya_sharma',
        doctorId: 'doc_ananya',
        name: 'Dr. Priya Sharma',
        specialty: 'Orthopedic Specialist',
        rating: 4.8,
        isVerified: true,
        clinic: 'One Medical South',
        experience: '8 yrs exp',
        nextAvailable: 'Next: Today, 4:00 PM',
        distance: '5.8 km',
        imageName: 'doctor_ananya',
        category: 'Orthopedic',
        isSaved: true,
      },
    ],
    exploreFooter: {
      title: 'Looking for someone else?',
      subtitle: 'Explore our directory of world-class specialists in your area.',
      buttonText: 'Explore All Specialists',
    },
  },
  notificationPreferencesDetails: {
    headerTitle: 'Notifications Preference',
    enableNotificationsCard: {
      title: 'Enable Notifications',
      description: 'Receive important updates about your appointments and recovery.',
      defaultState: true,
    },
    sections: [
      {
        id: 'appointments',
        title: 'APPOINTMENTS',
        items: [
          { id: 'upcoming_reminder', title: 'Upcoming Appointment Reminder', defaultState: true },
          { id: 'appt_confirmation', title: 'Appointment Confirmation', defaultState: true },
          { id: 'appt_rescheduled', title: 'Appointment Rescheduled', defaultState: true },
          { id: 'appt_cancelled', title: 'Appointment Cancelled', defaultState: true },
        ],
      },
      {
        id: 'recovery',
        title: 'RECOVERY',
        items: [
          { id: 'exercise_reminder', title: "Today's Exercise Reminder", defaultState: true },
          { id: 'program_updates', title: 'Recovery Program Updates', defaultState: true },
          { id: 'weekly_summary', title: 'Weekly Progress Summary', defaultState: true },
          { id: 'achievement_notifs', title: 'Achievement Notifications', defaultState: true },
        ],
      },
      {
        id: 'reports_payments',
        title: 'REPORTS & PAYMENTS',
        items: [
          { id: 'new_reports', title: 'New Medical Reports', defaultState: true },
          { id: 'payment_confirm', title: 'Payment Confirmation', defaultState: true },
          { id: 'invoice_available', title: 'Invoice Available', defaultState: false },
        ],
      },
      {
        id: 'marketing',
        title: 'MARKETING',
        items: [
          { id: 'health_tips', title: 'Health Tips', defaultState: false },
          { id: 'new_features', title: 'New Features', defaultState: false },
          { id: 'promotions', title: 'Promotions', defaultState: false },
        ],
      },
    ],
    resetButtonText: 'Reset to Default',
    footerSyncText: 'Changes will be synced across all your devices.',
  },
  privacySecurityDetails: {
    headerTitle: 'Privacy & Security',
    sections: {
      accountSecurity: {
        title: 'ACCOUNT SECURITY',
        items: {
          faceId: 'Face ID / Touch ID Login',
          twoStep: 'Two-Step Verification',
          twoStepStatus: 'On',
          changeMobile: 'Change Mobile Number',
          trustedDevices: 'Manage Trusted Devices',
        },
      },
      privacy: {
        title: 'PRIVACY',
        items: {
          dataSharing: 'Manage Data Sharing',
          downloadData: 'Download My Data',
          privacyPolicy: 'Privacy Policy',
          termsConditions: 'Terms & Conditions',
        },
      },
      sessionManagement: {
        title: 'SESSION MANAGEMENT',
        currentDeviceName: 'iPhone 16 Pro',
        currentDeviceDetails: 'Current Device • Today, 10:45 AM',
        viewActiveDevices: 'View Active Devices',
        signOutOthers: 'Sign Out From Other Devices',
      },
      deleteAccount: {
        title: 'Delete Account',
        description: 'Deleting your account will permanently remove all health records and profile information from our servers.',
      },
    },
  },
  changeMobileNumberDetails: {
    headerTitle: 'Change Mobile Number',
    securityUpdateTag: 'SECURITY UPDATE',
    securityUpdateDescription:
      'Update your contact details to ensure you receive appointment alerts and health reports.',
    currentNumberLabel: 'Current Number',
    registeredMobileLabel: 'Registered Mobile Number',
    currentPhoneNumber: '+91 98765 43210',
    verifiedBadgeText: 'VERIFIED',
    newNumberLabel: 'New Mobile Number',
    newNumberPlaceholder: 'Enter new mobile number',
    countryCodeDefault: '+91',
    verificationNoticePrefix: "We'll send a ",
    verificationNoticeBold: 'verification code',
    verificationNoticeSuffix:
      ' to your new mobile number before updating your account. This helps keep your medical records secure.',
    continueButtonText: 'Continue',
  },
  deleteAccountScreenDetails: {
    headerTitle: 'Delete Account',
    heroTitle: 'Delete Your Account',
    heroSubtitle: 'Deleting your account is permanent\nand cannot be undone.',
    whatHappensTitle: 'WHAT HAPPENS',
    whatHappensItems: [
      'Your account will be permanently deleted.',
      'Saved specialists will be removed.',
      'Notification preferences will be reset.',
      'Future appointments will be cancelled according to the clinic\'s cancellation policy.',
    ],
    legalNoticeText:
      'Medical records already maintained by the clinic may continue to be retained if required by applicable laws or regulations. Your app account will be removed, but clinical record retention may follow legal and healthcare requirements.',
    needBreakTitle: 'Need a break?',
    needBreakSubtitle: 'You can simply sign out and return anytime.',
    signOutButtonText: 'Sign Out',
    contactSupportText: 'Contact Support',
    checkboxLabel: 'I understand that this action is permanent.',
    deleteAccountButtonText: 'Delete Account',
  },
  helpSupportDetails: {
    headerTitle: 'Help & Support',
    hero: {
      title: 'How can we help you today?',
      subtitle: 'Find answers, contact our 24/7 care team, or get assistance with your recovery plan.',
      searchPlaceholder: 'Search FAQs, topics or keywords...',
    },
    quickContactSectionTitle: 'DIRECT CONTACT CHANNELS',
    contactOptions: [
      {
        id: 'chat',
        title: 'Chat with Care Team',
        subtitle: 'Average response time < 2 mins',
        icon: 'chatbubbles-outline',
        badge: '24/7 ONLINE',
        badgeBg: '#DCFCE7',
        badgeColor: '#166534',
        actionText: 'Start Live Chat',
      },
      {
        id: 'phone',
        title: 'Call Customer Support',
        subtitle: '+91 1800-123-4567 • Mon-Sun 8 AM - 10 PM',
        icon: 'call-outline',
        badge: 'TOLL FREE',
        badgeBg: '#EFF6FF',
        badgeColor: '#1E40AF',
        actionText: 'Call Now',
      },
      {
        id: 'email',
        title: 'Email Support Team',
        subtitle: 'support@onemedical.com • Reply within 2 hrs',
        icon: 'mail-outline',
        badge: 'EMAIL',
        badgeBg: '#F3E8FF',
        badgeColor: '#6B21A8',
        actionText: 'Send Email',
      },
      {
        id: 'callback',
        title: 'Request Call Back',
        subtitle: 'Have a care coordinator call you at your convenient time',
        icon: 'time-outline',
        badge: 'SCHEDULE',
        badgeBg: '#FEF3C7',
        badgeColor: '#92400E',
        actionText: 'Request Call',
      },
    ],
    faqSectionTitle: 'FREQUENTLY ASKED QUESTIONS',
    faqCategories: [
      { id: 'all', label: 'All FAQs' },
      { id: 'bookings', label: 'Appointments' },
      { id: 'recovery', label: 'Recovery & Exercises' },
      { id: 'payments', label: 'Billing & Refunds' },
      { id: 'account', label: 'Account & Security' },
    ],
    faqs: [
      {
        id: 'faq_1',
        category: 'bookings',
        question: 'How do I reschedule or cancel my appointment?',
        answer: 'You can reschedule or cancel an appointment up to 2 hours prior to the scheduled start time. Go to "My Bookings", select your upcoming session, and tap "Reschedule" or "Cancel Booking".',
      },
      {
        id: 'faq_2',
        category: 'bookings',
        question: 'What should I prepare for a Home Visit appointment?',
        answer: 'Please ensure a clean, quiet space with enough room for a treatment couch or exercise mat. Keep your previous medical reports and X-rays handy for the therapist.',
      },
      {
        id: 'faq_3',
        category: 'recovery',
        question: 'How do I track my daily exercise completion?',
        answer: 'Navigate to the "Recovery" tab on the bottom menu. Select today\'s session, complete each exercise set, and tap "Complete Exercise". Your progress streak will update automatically.',
      },
      {
        id: 'faq_4',
        category: 'recovery',
        question: 'What if I feel pain while performing an exercise?',
        answer: 'Stop the exercise immediately if you experience sharp or severe pain. Gentle discomfort is normal during rehabilitation, but pain is a sign to pause. Contact your therapist via live chat for guidance.',
      },
      {
        id: 'faq_5',
        category: 'payments',
        question: 'How can I get an official tax invoice for insurance claims?',
        answer: 'Go to Profile > Payments & Invoices. Select the invoice from your past bookings and tap "Download Invoice" to save a PDF copy formatted for health insurance reimbursement.',
      },
      {
        id: 'faq_6',
        category: 'payments',
        question: 'What is the refund timeline for cancelled appointments?',
        answer: 'Refunds for online payments cancelled in accordance with our policy are processed automatically to your original payment method within 3 to 5 business days.',
      },
      {
        id: 'faq_7',
        category: 'account',
        question: 'How do I update my mobile phone number?',
        answer: 'Go to Profile > Account Settings > Privacy & Security > Change Mobile Number. Enter your new mobile number and verify it with the 6-digit OTP sent to your new number.',
      },
      {
        id: 'faq_8',
        category: 'account',
        question: 'Is my medical data kept private and secure?',
        answer: 'Yes! ONE MEDICAL uses 256-bit HIPAA-compliant encryption to safeguard your health records, appointment notes, and personal information.',
      },
    ],
    selfServiceSectionTitle: 'SELF-SERVICE & RESOURCES',
    selfServiceItems: [
      {
        id: 'user_guide',
        title: 'App User Guide & Tutorials',
        subtitle: 'Watch video walkthroughs on booking sessions and exercise routines',
        icon: 'play-circle-outline',
      },
      {
        id: 'feedback',
        title: 'Give Feedback & Suggestions',
        subtitle: 'Help us improve ONE MEDICAL with your valuable feedback',
        icon: 'create-outline',
      },
      {
        id: 'report_bug',
        title: 'Report a Technical Issue',
        subtitle: 'Report bugs or unexpected app behavior to our tech team',
        icon: 'bug-outline',
      },
    ],
    emergencyNoticeTitle: 'MEDICAL EMERGENCY NOTICE',
    emergencyNoticeText: 'If you are experiencing a life-threatening medical emergency or severe acute chest pain, please call 112 / 108 immediately or go to the nearest hospital emergency room.',
  },
  aboutDetails: {
    headerTitle: 'About',
    brandName: 'ONE MEDICAL',
    tagline: 'Recover Better. Move Stronger.',
    versionText: 'Version 1.0.0',
    ourMissionTitle: 'Our Mission',
    ourMissionDescription:
      'ONE MEDICAL empowers your recovery journey through a clinical-grade digital experience. We seamlessly bridge the gap between you and world-class physiotherapy, offering seamless appointment booking, personalized rehabilitation programs, and a direct, secure line to your dedicated therapist.',
    menuLinks: [
      { id: 'privacy_policy', title: 'Privacy Policy', icon: 'shield-checkmark-outline' },
      { id: 'terms_conditions', title: 'Terms & Conditions', icon: 'document-text-outline' },
      { id: 'open_source', title: 'Open Source Licenses', icon: 'ribbon-outline' },
      { id: 'website', title: 'Website', icon: 'globe-outline' },
    ],
    connectWithUsTitle: 'CONNECT WITH US',
    socialLinks: [
      { id: 'instagram', title: 'Instagram', icon: 'camera-outline' },
      { id: 'facebook', title: 'Facebook', icon: 'logo-facebook' },
      { id: 'linkedin', title: 'LinkedIn', icon: 'briefcase-outline' },
    ],
    copyrightText: '© 2024 ONE MEDICAL Physiotherapy Management',
    officeAddressLine1: 'CLINIC HEAD OFFICE: 1200 HEALTH PLAZA, LEVEL 4',
    officeAddressLine2: 'SAN FRANCISCO, CA 94103',
  },
} as const;

export type StringsType = typeof Strings;


