import type { Program, RecentlyEditedItem, PopularTemplateItem } from './types';

export const INITIAL_PROGRAMS: Program[] = [
  {
    id: 'prog-1',
    title: 'Post-ACL Recovery',
    description: 'Comprehensive 12-week rehabilitation protocol.',
    status: 'published',
    bodyAreaTag: 'Knee Recovery',
    coverImage: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&w=800&q=80',
    duration: '12 Weeks',
    difficulty: 'Intermediate',
    activePatients: 428,
    completionRate: '82%',
    updatedAt: '2 hours ago',
    type: 'Rehabilitation',
    exercisesCount: 18,
  },
  {
    id: 'prog-2',
    title: 'Lower Back Stability',
    description: 'Core strengthening and postural alignment focus.',
    status: 'draft',
    bodyAreaTag: 'Lumbar Stability',
    coverImage: 'https://images.unsplash.com/photo-1530497610245-94d3c16cda28?auto=format&fit=crop&w=800&q=80',
    duration: '8 Weeks',
    difficulty: 'Beginner',
    activePatients: '--',
    completionRate: 'N/A',
    updatedAt: '1 day ago',
    type: 'Core Stability',
    exercisesCount: 12,
  },
  {
    id: 'prog-3',
    title: 'Cervical Mobility',
    description: 'Targeted stretches for chronic neck tension.',
    status: 'published',
    bodyAreaTag: 'Neck/Spine',
    coverImage: 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&w=800&q=80',
    duration: '4 Weeks',
    difficulty: 'Beginner',
    activePatients: 156,
    completionRate: '94%',
    updatedAt: '3 days ago',
    type: 'Mobility',
    exercisesCount: 10,
  },
  {
    id: 'prog-4',
    title: 'Rotator Cuff Rehab',
    description: 'Shoulder stability and range of motion restoration.',
    status: 'published',
    bodyAreaTag: 'Shoulder',
    coverImage: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=800&q=80',
    duration: '6 Weeks',
    difficulty: 'Intermediate',
    activePatients: 210,
    completionRate: '88%',
    updatedAt: '4 days ago',
    type: 'Rehabilitation',
    exercisesCount: 14,
  },
  {
    id: 'prog-5',
    title: 'Hamstring Strain Protocol',
    description: 'Eccentric strengthening for Grade 1 & 2 hamstring injuries.',
    status: 'draft',
    bodyAreaTag: 'Leg/Thigh',
    coverImage: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=800&q=80',
    duration: '6 Weeks',
    difficulty: 'Intermediate',
    activePatients: '--',
    completionRate: 'N/A',
    updatedAt: '5 days ago',
    type: 'Rehabilitation',
    exercisesCount: 15,
  },
  {
    id: 'prog-6',
    title: 'Ankle Proprioception',
    description: 'Balance and neuromuscular training post-sprain.',
    status: 'published',
    bodyAreaTag: 'Ankle/Foot',
    coverImage: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&w=800&q=80',
    duration: '3 Weeks',
    difficulty: 'Beginner',
    activePatients: 95,
    completionRate: '91%',
    updatedAt: '1 week ago',
    type: 'Balance',
    exercisesCount: 8,
  },
];

export const RECENTLY_EDITED: RecentlyEditedItem[] = [
  {
    id: 'rec-1',
    title: 'Shoulder Impingement',
    modifiedTime: 'Modified 2h ago',
    iconType: 'shoulder',
  },
  {
    id: 'rec-2',
    title: 'Hamstring Strain Level 2',
    modifiedTime: 'Modified 5h ago',
    iconType: 'hamstring',
  },
];

export const POPULAR_TEMPLATES: PopularTemplateItem[] = [
  {
    id: 'pop-1',
    title: 'Universal Warm-up',
    usageCount: 18,
  },
  {
    id: 'pop-2',
    title: 'Thoracic Opening',
    usageCount: 12,
  },
];
